/* ══════════════════════════════════════════════
   СТРОЙ ГРУПП — Shared JS
   Handles: lang switcher, FAQ accordion, smooth scroll
══════════════════════════════════════════════ */

const TG_LINK = 'https://t.me/+971589552882';

/* ── TRANSLATIONS ── */
const T = {
  ru: {
    'page.suffix':  '| СтройГрупп',
    'nav.home':     'Главная',
    'nav.services': 'Услуги',
    'nav.prices':   'Цены',
    'nav.portfolio':'Портфолио',
    'nav.blog':     'Блог',
    'nav.contacts': 'Контакты',
    'nav.cosmetic': 'Косметический ремонт',
    'nav.capital':  'Капитальный ремонт',
    'nav.design':   'Дизайнерский ремонт',
    'hdr.tg':       'Написать',
    'footer.desc':  'Профессиональный ремонт квартир в Москве с 2012 года. Гарантия 3 года.',
    'footer.services': 'Услуги',
    'footer.company':  'Компания',
    'footer.info':     'Информация',
    'footer.copy':  '© 2024 СтройГрупп. Все права защищены.',
    'footer.policy':'Политика конфиденциальности',
    'faq.btn.open': '+',
    'cta.title':    'Готовы начать ремонт?',
    'cta.sub':      'Напишите нам в Telegram — рассчитаем стоимость бесплатно',
    'cta.btn':      'Написать в Telegram',
    workerForms: ['мастер','мастера','мастера','мастера','мастеров','мастеров','мастеров','мастеров','мастеров','мастеров'],
    roomNames: ['Студия','1-комнатная','2-комнатная','3-комнатная'],
    roomSubs: ['до 35 м² — компактный вариант','35–50 м² — стандарт','50–75 м² — семейная квартира','75–110 м² — просторная квартира'],
    repairNames: ['Косметический','Капитальный','Дизайнерский'],
    vatText: (vat, total) => `+ НДС 20% (${vat}) = ${total} с НДС`,
    teamText: (n) => `Бригада ${n} чел.`,
    sqm: 'м²',
    'not.selected': 'Не выбран',
    'result.hint': 'Выберите тип ремонта для расчёта',
    'result.note': 'Точная смета — после выезда специалиста',
    'workers.weeks': 'нед.',
    'workers.dur': 'Срок: ~',
    'services.h1': 'Услуги по ремонту квартир',
    'services.sub': 'Полный цикл отделочных работ. От косметического освежения до премиального дизайнерского ремонта под ключ.',
    'uslugi.tag1': 'Что мы делаем',
    'uslugi.tag2': 'Основные услуги',
    'uslugi.tag3': 'Дополнительные работы',
    'uslugi.tag4': 'Наши преимущества',
    'uslugi.tag5': 'Вопросы и ответы',
    'uslugi.h2.1': 'Виды ремонта квартир',
    'uslugi.h2.2': 'Отдельные виды работ',
    'uslugi.h2.3': 'Почему выбирают СтройГрупп',
    'uslugi.h2.4': 'Часто задаваемые вопросы об услугах',
    'uslugi.cta.h2': 'Получите бесплатную консультацию',
    'uslugi.p1': 'Выберите формат, который подходит вашей квартире и бюджету',
    'uslugi.p2': 'Выполним конкретные задачи без полного ремонта квартиры',
    'uslugi.p3': 'Мы работаем на результат и строим долгосрочные отношения с клиентами',
    'uslugi.cta.p': 'Расскажите о вашем проекте в Telegram — ответим в течение 15 минут, бесплатно рассчитаем стоимость ремонта',
    'uslugi.price.cos': 'от 110 AED/м²',
    'uslugi.price.cap': 'от 240 AED/м²',
    'uslugi.price.des': 'от 480 AED/м²',
    'uslugi.feat1': 'Ремонт ванной комнаты',
    'uslugi.feat2': 'Ремонт кухни',
    'uslugi.feat3': 'Электромонтаж',
    'uslugi.feat4': 'Сантехнические работы',
    'uslugi.feat5': 'Натяжные потолки',
    'uslugi.feat6': 'Демонтажные работы',
    'uslugi.btn.price': 'Узнать цену',
    'uslugi.adv1': 'Фиксированная смета',
    'uslugi.adv2': 'Гарантия 3 года',
    'uslugi.adv3': 'Собственные бригады',
    'uslugi.adv4': 'Соблюдение сроков',
    'uslugi.adv5': 'Закупка материалов',
    'uslugi.adv6': 'Онлайн-отчётность',
    'uslugi.stat1': 'проектов',
    'uslugi.stat2': 'на рынке',
    'uslugi.stat3': 'гарантия',
    'uslugi.stat4': 'довольных клиентов',
    'btn.more': 'Подробнее',
    'btn.estimate': 'Получить смету бесплатно',
    'word.free': 'Бесплатно',
    'word.warranty': 'Гарантия',
    'uslugi.faq1.q': 'Какие виды ремонта вы выполняете?',
    'uslugi.faq1.a': 'Мы выполняем все виды ремонта квартир: косметический (от 110 AED/м²), капитальный (от 240 AED/м²) и дизайнерский (от 480 AED/м²). Также делаем отдельные виды работ — ремонт ванной комнаты и кухни, замену электрики и сантехники, монтаж натяжных потолков, демонтажные работы.',
    'uslugi.faq2.q': 'Работаете ли вы под ключ?',
    'uslugi.faq2.a': 'Да, основной наш формат — ремонт квартир под ключ. Вы получаете полностью готовую квартиру: от первого гвоздя до финишной уборки. Мы берём на себя организацию всех работ, закупку материалов, вывоз мусора.',
    'uslugi.faq3.q': 'Как быстро вы можете начать ремонт?',
    'uslugi.faq3.a': 'Обычно мы начинаем работы в течение 5–7 рабочих дней после подписания договора и внесения аванса. Замер и составление сметы — бесплатно, как правило в день обращения или на следующий день.',
    'uslugi.faq4.q': 'Даёте ли вы гарантию на ремонтные работы?',
    'uslugi.faq4.a': 'Да, мы даём письменную гарантию 3 года на все выполненные ремонтные работы. Гарантия прописывается в договоре. Если выявятся дефекты по нашей вине — устраним бесплатно в течение 5 рабочих дней.',
    'uslugi.faq5.q': 'В каких районах вы работаете?',
    'uslugi.faq5.a': 'Работаем по всей Москве и Подмосковью. Выезд мастера на замер — бесплатно. Принимаем заказы также из других регионов — обсудим детали в Telegram.',
    // common new keys
    'btn.prices':    'Посмотреть цены',
    'btn.order':     'Заказать',
    'btn.pricelist': 'Полный прайс-лист',
    'tbl.type':      'Тип квартиры',
    'tbl.area':      'Площадь',
    'tbl.cost':      'Стоимость работ',
    'tbl.term':      'Срок',
    'kap.stat1':     'за м²',
    'kap.stat2':     'срок работ',
    'kap.stat3':     'гарантия',
    'kap.stat4':     'замер и смета',
    // kapitalnyy-remont keys
    'kap.tag.hero':  'Ремонт с нуля',
    'kap.h1':        'Капитальный ремонт квартиры',
    'kap.sub':       'Полный цикл ремонтных работ: от демонтажа до финишной отделки. Новая электрика, сантехника, стяжка, штукатурка — квартира обновлена на 15–20 лет.',
    'kap.tag2':      'Что это такое',
    'kap.h2.1':      'Что такое капитальный ремонт квартиры',
    'kap.aside.h3':  'Когда нужен капитальный ремонт?',
    'kap.tag3':      'Состав работ',
    'kap.h2.2':      'Что входит в капитальный ремонт',
    'kap.p2':        'Полный перечень работ при капитальном ремонте квартиры под ключ',
    'kap.work1':     'Демонтаж',
    'kap.work2':     'Черновые работы',
    'kap.work3':     'Электрика',
    'kap.work4':     'Сантехника',
    'kap.work5':     'Шпаклёвка и отделка',
    'kap.work6':     'Завершение',
    'kap.tag4':      'Этапы работ',
    'kap.h2.3':      'Этапы капитального ремонта квартиры',
    'kap.p3':        'Последовательный и контролируемый процесс от подписания договора до передачи ключей',
    'kap.step1':     'Замер, смета и договор',
    'kap.step2':     'Демонтаж и подготовка',
    'kap.step3':     'Скрытые работы',
    'kap.step4':     'Черновая отделка',
    'kap.step5':     'Финишная отделка',
    'kap.step6':     'Сдача объекта',
    'kap.tag5':      'Стоимость',
    'kap.h2.4':      'Цены на капитальный ремонт квартиры',
    'kap.p4':        'Фиксированная стоимость работ — цена не изменится в процессе ремонта',
    'kap.note':      '* Стоимость указана за работы без учёта материалов. Точную цену узнайте после бесплатного замера. Стоимость материалов при капитальном ремонте зависит от выбранных отделочных материалов и марки сантехники.',
    'kap.tag6':      'Материалы',
    'kap.h2.5':      'Материалы для капитального ремонта',
    'kap.p5':        'Работаем с проверенными производителями и помогаем выбрать оптимальные материалы под ваш бюджет',
    'kap.mat1':      'Эконом-сегмент',
    'kap.mat2':      'Средний сегмент',
    'kap.mat3':      'Премиум',
    'kap.tag7':      'Вопросы и ответы',
    'kap.h2.6':      'Частые вопросы о капитальном ремонте',
    'kap.faq1.q':    'Сколько стоит капитальный ремонт квартиры?',
    'kap.faq1.a':    'Стоимость от 240 AED/м². Студия — от 8 400 AED, однокомнатная — от 12 000 AED, двухкомнатная — от 19 200 AED, трёхкомнатная — от 26 000 AED. Материалы не включены.',
    'kap.faq2.q':    'Сколько длится капитальный ремонт?',
    'kap.faq2.a':    'От 6 до 16 недель в зависимости от площади: однокомнатная — 6–8 недель, двухкомнатная — 8–12 недель, трёхкомнатная — 12–16 недель.',
    'kap.faq3.q':    'Чем капитальный ремонт отличается от косметического?',
    'kap.faq3.a':    'Косметический — обновление поверхностей без изменения инженерных систем. Капитальный — полное обновление с заменой электрики, сантехники, стяжкой и штукатуркой. Результат служит 15–20 лет.',
    'kap.faq4.q':    'Нужно ли согласование при капитальном ремонте?',
    'kap.faq4.a':    'Если не меняете планировку — согласование не нужно. При сносе или возведении перегородок, переносе кухни — нужно согласование. Помогаем с документами.',
    'kap.faq5.q':    'Можно ли поэтапно оплачивать ремонт?',
    'kap.faq5.a':    'Да, стандартная схема: 30% аванс, 40% после черновых работ, 30% при финальной сдаче. График прописывается в договоре.',
    'kap.tag8':      'Другие услуги',
    'kap.h2.7':      'Другие виды ремонта квартир',
    'kap.allsvc':    'Все услуги',
    'kap.viewall':   'Смотреть всё',
    'kap.onrequest': 'По запросу',
    'kap.cta.h2':    'Готовы обсудить ремонт квартиры?',
    'kap.cta.p':     'Напишите нам в Telegram — бесплатно рассчитаем стоимость капитального ремонта и ответим на все вопросы. Выезд на замер в день обращения.',
    'kap.desc.p1':   'Капитальный ремонт — это комплексное обновление квартиры «с нуля»: полный демонтаж старых покрытий и инженерных систем, выравнивание всех поверхностей, замена электрики и сантехники, и только затем — финишная отделка.',
    'kap.desc.p2':   'В отличие от косметического, при капитальном ремонте обновляется всё скрытое: трубы холодного и горячего водоснабжения, канализация, электрическая разводка. Именно это обеспечивает долговечность — правильно сделанный капитальный ремонт служит 15–20 лет.',
    'kap.desc.p3':   'Обязательный этап — стяжка пола. Без неё невозможно добиться ровного основания для напольного покрытия, тёплого пола и правильного уклона в санузлах. Стяжку делаем по маякам с точностью до 2 мм на метр.',
    'kap.desc.p4':   'Выравнивание стен штукатуркой — ещё один ключевой процесс. В типовых панельных домах стены часто заваливаются на 2–5 см. Качественная машинная штукатурка создаёт идеально ровную поверхность для любого финишного покрытия.',
    'kap.desc.p5':   'Электрика при капитальном ремонте прокладывается в штробах или под штукатуркой — все провода скрытые. Мы рассчитываем нагрузки под современную технику и предусматриваем достаточное количество розеток в каждой комнате.',
    'kap.desc.p6':   'Результат капитального ремонта от СтройГрупп — квартира, в которой всё работает правильно и выглядит отлично. Мы даём гарантию 3 года на все выполненные работы.',
    'kap.when.li1':  'Квартира не ремонтировалась 15+ лет',
    'kap.when.li2':  'Требуется замена электрики или труб',
    'kap.when.li3':  'Стены и полы сильно неровные',
    'kap.when.li4':  'Планируется перепланировка',
    'kap.when.li5':  'Вторичное жильё перед заездом',
    'kap.when.li6':  'Новостройка без отделки (черновая)',
    'kap.when.li7':  'Хотите сделать всё один раз и надолго',
    'kap.demo.1':    'Снятие обоев и плитки',
    'kap.demo.2':    'Демонтаж напольных покрытий',
    'kap.demo.3':    'Снос ненесущих перегородок',
    'kap.demo.4':    'Удаление старой стяжки (при необходимости)',
    'kap.demo.5':    'Вывоз строительного мусора',
    'kap.rough.1':   'Стяжка пола по маякам',
    'kap.rough.2':   'Машинная штукатурка стен',
    'kap.rough.3':   'Выравнивание потолков',
    'kap.rough.4':   'Возведение гипсокартонных перегородок',
    'kap.rough.5':   'Устройство тёплого пола',
    'kap.elec.1':    'Замена электрощита',
    'kap.elec.2':    'Полная замена проводки',
    'kap.elec.3':    'Разводка розеток и выключателей',
    'kap.elec.4':    'Монтаж освещения',
    'kap.elec.5':    'Подключение электроплиты и бойлера',
    'kap.plumb.1':   'Замена труб водоснабжения',
    'kap.plumb.2':   'Замена канализационных труб',
    'kap.plumb.3':   'Установка унитаза, ванны/душа',
    'kap.plumb.4':   'Подключение радиаторов отопления',
    'kap.plumb.5':   'Монтаж водонагревателя',
    'kap.trim.1':    'Финишная шпаклёвка стен',
    'kap.trim.2':    'Поклейка обоев или покраска',
    'kap.trim.3':    'Укладка плитки в санузле и кухне',
    'kap.trim.4':    'Укладка ламината или паркета',
    'kap.trim.5':    'Монтаж потолков',
    'kap.comp.1':    'Установка межкомнатных дверей',
    'kap.comp.2':    'Монтаж плинтусов и наличников',
    'kap.comp.3':    'Установка розеток и выключателей',
    'kap.comp.4':    'Финишная уборка',
    'kap.comp.5':    'Сдача объекта по акту с гарантией',
    'kap.step1.p':   'Бесплатный выезд замерщика. Составление подробной сметы с разбивкой по видам работ и материалам. Подписание договора с фиксированной ценой, сроками и перечнем работ.',
    'kap.step2.p':   'Демонтаж всех старых покрытий, перегородок, старой электрики и сантехники. Вывоз мусора. Оценка состояния оснований и корректировка планов при необходимости.',
    'kap.step3.p':   'Прокладка новой электропроводки, замена труб водоснабжения и канализации. Все коммуникации прячутся в стены и пол до начала отделочных работ.',
    'kap.step4.p':   'Стяжка пола по маякам, машинная штукатурка стен, выравнивание потолков. Эти работы формируют ровную основу для финишного покрытия. Обязательная выдержка технологических пауз.',
    'kap.step5.p':   'Шпаклёвка, поклейка обоев или покраска, укладка плитки в санузле, укладка ламината или паркета в комнатах, монтаж потолков, установка дверей и плинтусов.',
    'kap.step6.p':   'Установка розеток, выключателей, светильников, сантехнических приборов. Финишная уборка. Приёмка с составлением акта и выдачей гарантийного талона на 3 года.',
    'kap.mat1.p':    'Российские и белорусские производители: Knauf, Bergauf, Ceresit. Хорошее качество при доступной цене. Рекомендуем для квартир под сдачу в аренду.',
    'kap.mat2.p':    'Kerama Marazzi, Atlas, Glims — проверенные бренды с широким ассортиментом. Оптимальное соотношение цены и качества для жилого ремонта.',
    'kap.mat3.p':    'Weber, Mapei, Litokol, Schlueter — европейские материалы с расширенными характеристиками. Подходят для сложных условий эксплуатации и повышенных требований к качеству.',
    'kap.svc.cos.p': 'Быстрое обновление внешнего вида квартиры. Обои, покраска, ламинат, потолки. Оптимально при ограниченном бюджете.',
    'kap.svc.des.p': 'Авторский дизайн-проект, 3D-визуализация, элитные материалы. Ваша квартира как на страницах журнала.',
    'kap.svc.all.p': 'Ремонт ванной, кухни, замена электрики и сантехники, натяжные потолки и другие виды работ.',
    'term.6w':       '6 недель',
    'term.6_8w':     '6–8 недель',
    'term.8_12w':    '8–12 недель',
    'term.12_16w':   '12–16 недель',
    // kosmeticheskiy-remont keys
    'kos.tag.hero':  'Быстро и экономично',
    'kos.h1':        'Косметический ремонт квартиры',
    'kos.sub':       'Обновим вашу квартиру до неузнаваемости без глобального ремонта. Новые обои, покраска, ламинат, потолки — и квартира снова радует глаз.',
    'kos.tag2':      'Что это такое',
    'kos.h2.1':      'Что такое косметический ремонт квартиры',
    'kos.aside.h3':  'Когда подходит косметический ремонт?',
    'kos.tag3':      'Состав работ',
    'kos.h2.2':      'Что входит в косметический ремонт',
    'kos.p2':        'Полный перечень работ, которые мы выполняем в рамках косметического ремонта под ключ',
    'kos.work1':     'Стены',
    'kos.work2':     'Потолки',
    'kos.work3':     'Полы',
    'kos.work4':     'Двери и окна',
    'kos.work5':     'Санузел (базовый)',
    'kos.work6':     'Завершающие работы',
    'kos.tag4':      'Этапы работ',
    'kos.h2.3':      'Как мы делаем косметический ремонт',
    'kos.p3':        'Чёткий и понятный процесс от замера до сдачи объекта',
    'kos.step1':     'Замер и смета',
    'kos.step2':     'Договор и аванс',
    'kos.step3':     'Подготовка поверхностей',
    'kos.step4':     'Финишная отделка',
    'kos.tag5':      'Стоимость',
    'kos.h2.4':      'Цены на косметический ремонт квартиры',
    'kos.p4':        'Фиксированная стоимость работ — цена не изменится в процессе ремонта',
    'kos.note':      '* Стоимость указана за работы без учёта материалов. Точную цену узнайте после бесплатного замера. Стоимость материалов зависит от выбранных вами отделочных материалов.',
    'kos.tag6':      'Вопросы и ответы',
    'kos.h2.5':      'Частые вопросы о косметическом ремонте',
    'kos.faq1.q':    'Сколько стоит косметический ремонт квартиры?',
    'kos.faq1.a':    'От 110 AED/м². Студия — от 3 400 AED, однокомнатная — от 4 800 AED, двухкомнатная — от 7 600 AED, трёхкомнатная — от 10 400 AED. Материалы не включены.',
    'kos.faq2.q':    'Сколько времени занимает косметический ремонт?',
    'kos.faq2.a':    'Косметический ремонт однокомнатной квартиры занимает 2–3 недели. Двухкомнатная — 3–4 недели. Сроки прописываются в договоре.',
    'kos.faq3.q':    'Что входит в косметический ремонт квартиры?',
    'kos.faq3.a':    'Поклейка обоев или покраска стен, укладка ламината, установка плинтусов, обновление потолков, покраска или замена дверей, укладка плитки в санузле.',
    'kos.faq4.q':    'Нужно ли вывозить мебель перед косметическим ремонтом?',
    'kos.faq4.a':    'Желательно освободить помещение от мебели или отодвинуть её к центру. Мы накрываем всё плёнкой. При полном выезде работы идут быстрее.',
    'kos.tag7':      'Другие услуги',
    'kos.h2.6':      'Нужен более основательный ремонт?',
    'kos.cta.h2':    'Хотите обновить квартиру?',
    'kos.cta.p':     'Напишите нам в Telegram — бесплатно рассчитаем стоимость косметического ремонта вашей квартиры. Ответим в течение 15 минут.',
    'kos.desc.p1':   'Косметический ремонт — это обновление внешнего вида квартиры без изменения планировки, конструктивных элементов и инженерных систем. Такой ремонт называют ещё «ремонт поверхностей» или «финишная отделка».',
    'kos.desc.p2':   'Главная цель косметического ремонта — сделать квартиру свежей и привлекательной. Обновляются все видимые поверхности: стены, потолок, пол, двери. При этом трубы, проводка и несущие конструкции не затрагиваются.',
    'kos.desc.p3':   'Косметический ремонт — оптимальный выбор, если квартира в целом находится в рабочем состоянии, но внешний вид её устарел. Обои пожелтели, полы скрипят, потолки посерели — это классические признаки того, что пора сделать косметику.',
    'kos.desc.p4':   'Такой ремонт значительно дешевле капитального и занимает существенно меньше времени. Среднестатистическую однокомнатную квартиру мы ремонтируем за 2–3 недели, а двухкомнатную — за 3–4 недели. Это позволяет минимизировать неудобства для жильцов.',
    'kos.desc.p5':   'В СтройГрупп мы подходим к косметическому ремонту профессионально: тщательно готовим поверхности, используем качественные материалы и соблюдаем технологии. Именно поэтому результат нашей работы выглядит как дорогой ремонт даже в скромном бюджете.',
    'kos.when.li1':  'Квартира после аренды — обновить внешний вид',
    'kos.when.li2':  'Плановое обновление каждые 5–10 лет',
    'kos.when.li3':  'Подготовка квартиры к продаже',
    'kos.when.li4':  'Новостройка с чистовой отделкой',
    'kos.when.li5':  'Ограниченный бюджет на ремонт',
    'kos.when.li6':  'Нет желания жить на стройке месяцами',
    'kos.walls.1':   'Шпаклёвка и выравнивание поверхностей',
    'kos.walls.2':   'Грунтование стен',
    'kos.walls.3':   'Поклейка обоев (виниловых, флизелиновых)',
    'kos.walls.4':   'Покраска стен в 2 слоя',
    'kos.walls.5':   'Декоративная штукатурка',
    'kos.ceil.1':    'Шпаклёвка потолка',
    'kos.ceil.2':    'Побелка или покраска потолка',
    'kos.ceil.3':    'Монтаж натяжного потолка',
    'kos.ceil.4':    'Монтаж потолочного плинтуса',
    'kos.ceil.5':    'Установка светильников',
    'kos.floor.1':   'Укладка ламината или паркетной доски',
    'kos.floor.2':   'Укладка линолеума',
    'kos.floor.3':   'Укладка ковролина',
    'kos.floor.4':   'Установка напольных плинтусов',
    'kos.floor.5':   'Пороги между комнатами',
    'kos.door.1':    'Покраска межкомнатных дверей',
    'kos.door.2':    'Замена межкомнатных дверей',
    'kos.door.3':    'Покраска оконных откосов',
    'kos.door.4':    'Установка наличников',
    'kos.door.5':    'Регулировка дверной фурнитуры',
    'kos.bath.1':    'Укладка плитки на пол и стены',
    'kos.bath.2':    'Замена смесителей и аксессуаров',
    'kos.bath.3':    'Замена унитаза и мойки',
    'kos.bath.4':    'Покраска потолка',
    'kos.bath.5':    'Установка зеркала и полок',
    'kos.fin.1':     'Замена розеток и выключателей',
    'kos.fin.2':     'Установка карнизов и штор',
    'kos.fin.3':     'Финишная уборка после ремонта',
    'kos.fin.4':     'Вывоз строительного мусора',
    'kos.fin.5':     'Сдача объекта по акту',
    'kos.step1.p':   'Выезжаем на объект бесплатно. Замеряем все помещения, оцениваем состояние поверхностей, обсуждаем ваши пожелания. Составляем подробную смету с разбивкой по работам и материалам.',
    'kos.step2.p':   'Подписываем договор с фиксированной ценой, перечнем работ и сроками. Вносите аванс 30% — и мы приступаем к закупке материалов и организации работ.',
    'kos.step3.p':   'Демонтируем старые покрытия: снимаем обои, плинтуса, при необходимости выравниваем поверхности. Защищаем мебель и окна плёнкой. Проводим грунтование.',
    'kos.step4.p':   'Поклейка обоев или покраска стен, укладка напольного покрытия, монтаж плинтусов, обновление потолков. Каждый этап выполняется по технологии и с контролем качества.',
    'kos.faq5.q':    'Можно ли жить в квартире во время косметического ремонта?',
    'kos.faq5.a':    'Технически можно, но некомфортно: шум, пыль, запах краски. Если квартира небольшая, лучше на время ремонта пожить у родственников или снять жильё. При ремонте по комнатам можно оставаться в незатронутой части квартиры. Мы стараемся минимизировать беспокойство — убираем за собой в конце каждого рабочего дня.',
    'kos.svc.cap.p': 'Полная замена инженерных систем, выравнивание стен и пола. Ремонт «с нуля» на долгие годы.',
    'kos.svc.des.p': 'Авторский дизайн-проект, элитные материалы, нестандартные решения. Ваша квартира — произведение искусства.',
    'kos.svc.all.p': 'Ремонт ванной, кухни, замена электрики и сантехники, натяжные потолки и другие отдельные виды работ.',
    'apt.studio':    'Студия / Комната',
    'apt.1room':     '1-комнатная',
    'apt.2room':     '2-комнатная',
    'apt.3room':     '3-комнатная',
    'term.2w':       '2 недели',
    'term.2_3w':     '2–3 недели',
    'term.3_4w':     '3–4 недели',
    'term.4_5w':     '4–5 недель',
    // dizaynersky-remont keys
    'diz.tag.hero':  'Премиальный формат',
    'diz.h1':        'Дизайнерский ремонт квартиры',
    'diz.sub':       'Авторский подход к каждому проекту. Мы создаём уникальные интерьеры, которые отражают вашу личность. Дизайн-проект, 3D-визуализация, элитные материалы и авторский надзор.',
    'diz.stat4':     'индивидуально',
    'diz.btn.discuss':    'Обсудить проект',
    'diz.btn.portfolio':  'Смотреть портфолио',
    'diz.btn.allportfolio': 'Смотреть всё портфолио',
    'diz.tag2':      'Состав услуги',
    'diz.h2.1':      'Что включает дизайнерский ремонт',
    'diz.p1':        'Полный пакет услуг — от концепции до финального декорирования',
    'diz.feat1':     'Авторский дизайн-проект',
    'diz.feat2':     '3D-визуализация',
    'diz.feat3':     'Подбор материалов',
    'diz.feat4':     'Авторский надзор',
    'diz.feat5':     'Нестандартные решения',
    'diz.feat6':     'Декорирование и меблировка',
    'diz.tag3':      'Примеры работ',
    'diz.h2.2':      'Дизайнерские проекты СтройГрупп',
    'diz.p2':        'Несколько примеров реализованных дизайнерских ремонтов',
    'diz.tag4':      'Этапы работ',
    'diz.h2.3':      'Как создаётся дизайнерский ремонт',
    'diz.p3':        'Прозрачный процесс от первой встречи до финальной фотосессии готового интерьера',
    'diz.step1':     'Дизайн-концепция',
    'diz.step2':     '3D-визуализация',
    'diz.step3':     'Рабочая документация',
    'diz.step4':     'Строительные работы',
    'diz.step5':     'Авторский надзор',
    'diz.step6':     'Декорирование и сдача',
    'diz.tag5':      'Стоимость',
    'diz.h2.4':      'Стоимость дизайнерского ремонта',
    'diz.price1.h3': 'Дизайн-проект',
    'diz.price2.h3': 'Дизайнерский ремонт',
    'diz.price3.h3': 'Декорирование',
    'diz.note':      '* Стоимость строительных работ не включает материалы. Точную смету составляем после разработки дизайн-проекта. Обсудите ваш проект с нами в Telegram.',
    'diz.tag6':      'Вопросы и ответы',
    'diz.h2.5':      'Частые вопросы о дизайнерском ремонте',
    'diz.faq1.q':    'Что входит в дизайнерский ремонт квартиры?',
    'diz.faq1.a':    'Дизайнерский ремонт включает: разработку авторского дизайн-проекта с 3D-визуализацией, составление рабочей документации, подбор и закупку элитных материалов, полный цикл строительных работ, авторский надзор дизайнера и финальное декорирование.',
    'diz.faq2.q':    'Сколько стоит дизайнерский ремонт квартиры?',
    'diz.faq2.a':    'Стоимость дизайнерского ремонта начинается от 480 AED/м² за строительные работы. Дизайн-проект — от 60 AED/м². Итоговая стоимость зависит от площади, сложности и уровня материалов.',
    'diz.faq3.q':    'Сколько времени занимает дизайнерский ремонт?',
    'diz.faq3.a':    'Разработка дизайн-проекта занимает 3–6 недель. Строительные работы — от 3 до 6 месяцев. Итого от первой встречи до передачи ключей — 4–8 месяцев.',
    'diz.faq4.q':    'Нужен ли дизайн-проект для ремонта?',
    'diz.faq4.a':    'Для дизайнерского ремонта — обязательно. Дизайн-проект позволяет видеть результат до начала работ, точно рассчитать материалы и избежать переделок.',
    'diz.faq5.q':    'Можно ли заказать только дизайн-проект без ремонта?',
    'diz.faq5.a':    'Да, мы разрабатываем дизайн-проекты отдельно. При совместном заказе дизайна и ремонта стоимость проекта снижается. Напишите в Telegram, чтобы обсудить условия.',
    'diz.tag7':      'Другие услуги',
    'diz.h2.6':      'Другие виды ремонта',
    'diz.cta.h2':    'Создадим ваш идеальный интерьер',
    'diz.cta.p':     'Расскажите о своих идеях в Telegram — наш дизайнер свяжется с вами, чтобы обсудить концепцию будущего интерьера. Консультация бесплатно.',
    'diz.cta.btn':   'Обсудить проект в Telegram',
    'diz.feat1.p':   'Разрабатываем концепцию интерьера с учётом ваших предпочтений, образа жизни и особенностей квартиры. Обмерный план, планировочное решение, расстановка мебели.',
    'diz.feat2.p':   'Фотореалистичная 3D-визуализация каждого помещения. Вы увидите, как будет выглядеть квартира, ещё до начала строительных работ. Можем вносить изменения.',
    'diz.feat3.p':   'Создаём комплектовочные ведомости с конкретными артикулами. Помогаем с закупкой у поставщиков по оптовым ценам. Только проверенные бренды и качественная продукция.',
    'diz.feat4.p':   'Дизайнер контролирует соответствие выполненных работ проекту на каждом этапе. Своевременно выявляет отклонения и даёт мастерам точные указания.',
    'diz.feat5.p':   'Многоуровневые потолки, скрытая подсветка, ниши и арки, эксклюзивные покрытия, встроенные шкафы по индивидуальным размерам. Всё, что сделает интерьер уникальным.',
    'diz.feat6.p':   'Финальное декорирование квартиры: текстиль, освещение, предметы декора. По запросу — подбор и расстановка мебели. Передаём вам полностью готовую квартиру.',
    'diz.step1.p':   'Встреча с дизайнером, брифинг, изучение ваших предпочтений. Обмеры квартиры. Разработка концепции и планировочных решений. Согласование общего направления.',
    'diz.step2.p':   'Фотореалистичная 3D-визуализация всех помещений. Вы видите квартиру ещё до начала работ. Вносим правки до полного согласования — ограничений нет.',
    'diz.step3.p':   'Рабочие чертежи для всех помещений: разрёзы, развёртки, спецификации. Комплектовочные ведомости с конкретными артикулами материалов. Закупка материалов.',
    'diz.step4.p':   'Полный цикл строительных и отделочных работ согласно проекту. Капитальный ремонт со всеми инженерными системами, финишная отделка по спецификации.',
    'diz.step5.p':   'Дизайнер регулярно посещает объект и контролирует соответствие работ проекту. Еженедельные фотоотчёты. Оперативное решение технических вопросов на месте.',
    'diz.step6.p':   'Расстановка мебели, текстиль, освещение, предметы декора. Финальная уборка. Профессиональная фотосессия готового интерьера. Передача ключей и гарантийного талона.',
    'diz.p1.li1':    'Концепция и планировка',
    'diz.p1.li2':    '3D-визуализация',
    'diz.p1.li3':    'Рабочие чертежи',
    'diz.p1.li4':    'Комплектовочные ведомости',
    'diz.p1.li5':    'Авторский надзор',
    'diz.p2.li1':    'Все работы капитального ремонта',
    'diz.p2.li2':    'Элитные материалы',
    'diz.p2.li3':    'Нестандартные конструкции',
    'diz.p2.li4':    'Встроенная мебель на заказ',
    'diz.p2.li5':    'Система умного дома',
    'diz.p3.li1':    'Подбор мебели',
    'diz.p3.li2':    'Текстиль и шторы',
    'diz.p3.li3':    'Освещение и люстры',
    'diz.p3.li4':    'Декор и аксессуары',
    'diz.p3.li5':    'Расстановка и стайлинг',
    'diz.svc.cos.p': 'Быстрое обновление квартиры без глобальных работ. Оптимально при ограниченном бюджете.',
    'diz.svc.cap.p': 'Полная замена всех инженерных систем и чистовая отделка. Надёжно на 15–20 лет.',
    'diz.svc.all.p': 'Ремонт ванной, кухни, замена электрики и сантехники, натяжные потолки.',
  },
  en: {
    'page.suffix':  '| BuildGroup',
    'nav.home':     'Home',
    'nav.services': 'Services',
    'nav.prices':   'Pricing',
    'nav.portfolio':'Portfolio',
    'nav.blog':     'Blog',
    'nav.contacts': 'Contacts',
    'nav.cosmetic': 'Cosmetic renovation',
    'nav.capital':  'Capital renovation',
    'nav.design':   'Designer renovation',
    'hdr.tg':       'Message us',
    'footer.desc':  'Professional apartment renovation in Moscow since 2012. 3-year warranty.',
    'footer.services': 'Services',
    'footer.company':  'Company',
    'footer.info':     'Info',
    'footer.copy':  '© 2024 BuildGroup. All rights reserved.',
    'footer.policy':'Privacy Policy',
    'cta.title':    'Ready to start renovation?',
    'cta.sub':      'Message us on Telegram — free estimate',
    'cta.btn':      'Message on Telegram',
    workerForms: ['worker','workers','workers','workers','workers','workers','workers','workers','workers','workers'],
    roomNames: ['Studio','1-room','2-room','3-room'],
    roomSubs: ['up to 35 m²','35–50 m²','50–75 m²','75–110 m²'],
    repairNames: ['Cosmetic','Capital','Designer'],
    vatText: (vat, total) => `+ VAT 20% (${vat}) = ${total} incl. VAT`,
    teamText: (n) => `Team of ${n}`,
    sqm: 'm²',
    'not.selected': 'Not selected',
    'result.hint': 'Select renovation type to calculate',
    'result.note': 'Exact estimate — after specialist visit',
    'workers.weeks': 'wks.',
    'workers.dur': 'Duration: ~',
    'services.h1': 'Apartment Renovation Services',
    'services.sub': 'Full cycle of finishing works. From cosmetic refresh to premium designer renovation.',
    'uslugi.tag1': 'What We Do',
    'uslugi.tag2': 'Main Services',
    'uslugi.tag3': 'Additional Works',
    'uslugi.tag4': 'Our Advantages',
    'uslugi.tag5': 'FAQ',
    'uslugi.h2.1': 'Types of Apartment Renovation',
    'uslugi.h2.2': 'Individual Services',
    'uslugi.h2.3': 'Why Choose BuildGroup',
    'uslugi.h2.4': 'Frequently Asked Questions',
    'uslugi.cta.h2': 'Get a Free Consultation',
    'uslugi.p1': 'Choose the format that suits your apartment and budget',
    'uslugi.p2': 'We handle specific tasks without a full renovation',
    'uslugi.p3': 'We work for results and build long-term client relationships',
    'uslugi.cta.p': 'Tell us about your project on Telegram — we reply within 15 minutes, free estimate',
    'uslugi.price.cos': 'from 110 AED/m²',
    'uslugi.price.cap': 'from 240 AED/m²',
    'uslugi.price.des': 'from 480 AED/m²',
    'uslugi.feat1': 'Bathroom Renovation',
    'uslugi.feat2': 'Kitchen Renovation',
    'uslugi.feat3': 'Electrical Works',
    'uslugi.feat4': 'Plumbing Works',
    'uslugi.feat5': 'Stretch Ceilings',
    'uslugi.feat6': 'Demolition Works',
    'uslugi.btn.price': 'Get a Quote',
    'uslugi.adv1': 'Fixed Estimate',
    'uslugi.adv2': '3-Year Warranty',
    'uslugi.adv3': 'In-House Teams',
    'uslugi.adv4': 'On-Time Delivery',
    'uslugi.adv5': 'Material Procurement',
    'uslugi.adv6': 'Online Progress Reports',
    'uslugi.stat1': 'projects',
    'uslugi.stat2': 'in business',
    'uslugi.stat3': 'warranty',
    'uslugi.stat4': 'happy clients',
    'btn.more': 'Learn More',
    'btn.estimate': 'Get Free Estimate',
    'word.free': 'Free',
    'word.warranty': 'Warranty',
    'uslugi.faq1.q': 'What types of renovation do you offer?',
    'uslugi.faq1.a': 'We offer all types of apartment renovation: cosmetic (from 110 AED/m²), capital (from 240 AED/m²) and designer (from 480 AED/m²). We also perform individual works — bathroom, kitchen, electrical, plumbing, stretch ceilings, demolition.',
    'uslugi.faq2.q': 'Do you offer turnkey renovation?',
    'uslugi.faq2.a': 'Yes, our main format is turnkey apartment renovation. You receive a fully finished apartment — from first nail to final clean-up. We handle all works, material procurement, and waste removal.',
    'uslugi.faq3.q': 'How quickly can you start?',
    'uslugi.faq3.a': 'We typically start within 5–7 business days after signing the contract and paying the deposit. Measuring and estimating are free — usually done on the day of inquiry or the next day.',
    'uslugi.faq4.q': 'Do you provide a warranty?',
    'uslugi.faq4.a': 'Yes, we provide a written 3-year warranty on all completed renovation works. The warranty is stated in the contract. If defects appear due to our fault, we fix them free of charge within 5 business days.',
    'uslugi.faq5.q': 'Which areas do you serve?',
    'uslugi.faq5.a': 'We work throughout Moscow and the surrounding region. The specialist visit for measurement is free. We also accept orders from other regions — discuss the details via Telegram.',
    // common new keys
    'btn.prices':    'View Pricing',
    'btn.order':     'Order',
    'btn.pricelist': 'Full Price List',
    'tbl.type':      'Apartment type',
    'tbl.area':      'Area',
    'tbl.cost':      'Works cost',
    'tbl.term':      'Duration',
    'kap.stat1':     'per m²',
    'kap.stat2':     'works duration',
    'kap.stat3':     'warranty',
    'kap.stat4':     'measure & estimate',
    // kapitalnyy-remont keys
    'kap.tag.hero':  'Full renovation',
    'kap.h1':        'Capital Apartment Renovation',
    'kap.sub':       'Full renovation cycle: from demolition to finishing. New electrical, plumbing, screed, plaster — apartment renewed for 15–20 years.',
    'kap.tag2':      'What it is',
    'kap.h2.1':      'What is capital renovation?',
    'kap.aside.h3':  'When is capital renovation needed?',
    'kap.tag3':      'Scope of works',
    'kap.h2.2':      'What\'s included in capital renovation',
    'kap.p2':        'Full list of works for turnkey capital renovation',
    'kap.work1':     'Demolition',
    'kap.work2':     'Rough works',
    'kap.work3':     'Electrical',
    'kap.work4':     'Plumbing',
    'kap.work5':     'Finishing & Trim',
    'kap.work6':     'Completion',
    'kap.tag4':      'Work stages',
    'kap.h2.3':      'Stages of capital renovation',
    'kap.p3':        'Controlled process from contract signing to key handover',
    'kap.step1':     'Measure, estimate & contract',
    'kap.step2':     'Demolition & preparation',
    'kap.step3':     'Hidden works',
    'kap.step4':     'Rough finishing',
    'kap.step5':     'Final finishing',
    'kap.step6':     'Handover',
    'kap.tag5':      'Pricing',
    'kap.h2.4':      'Capital renovation prices',
    'kap.p4':        'Fixed price — cost won\'t change during renovation',
    'kap.note':      '* Price is for works only, materials not included. Get exact price after a free measurement visit.',
    'kap.tag6':      'Materials',
    'kap.h2.5':      'Materials for capital renovation',
    'kap.p5':        'We work with trusted manufacturers and help choose optimal materials for your budget',
    'kap.mat1':      'Economy class',
    'kap.mat2':      'Mid-range',
    'kap.mat3':      'Premium',
    'kap.tag7':      'FAQ',
    'kap.h2.6':      'FAQ about capital renovation',
    'kap.faq1.q':    'How much does capital renovation cost?',
    'kap.faq1.a':    'Starting from 240 AED/m². Studio — from 8,400 AED, 1-room — from 12,000 AED, 2-room — from 19,200 AED, 3-room — from 26,000 AED. Materials not included.',
    'kap.faq2.q':    'How long does capital renovation take?',
    'kap.faq2.a':    '6 to 16 weeks depending on apartment size: 1-room — 6–8 weeks, 2-room — 8–12 weeks, 3-room — 12–16 weeks.',
    'kap.faq3.q':    'How is capital renovation different from cosmetic?',
    'kap.faq3.a':    'Cosmetic — surface renewal without changing engineering systems. Capital — full renovation with electrical, plumbing, screed and plaster replacement. Result lasts 15–20 years.',
    'kap.faq4.q':    'Is approval needed for capital renovation?',
    'kap.faq4.a':    'If you don\'t change the layout — no approval needed. If demolishing/building partitions or relocating kitchen — approval required. We help with documentation.',
    'kap.faq5.q':    'Can I pay in stages?',
    'kap.faq5.a':    'Yes, standard scheme: 30% advance, 40% after rough works, 30% at final handover. Payment schedule is stated in the contract.',
    'kap.tag8':      'Other services',
    'kap.h2.7':      'Other renovation types',
    'kap.allsvc':    'All services',
    'kap.viewall':   'View all',
    'kap.onrequest': 'On request',
    'kap.cta.h2':    'Ready to discuss your renovation?',
    'kap.cta.p':     'Message us on Telegram — we\'ll calculate the cost of capital renovation for free and answer all questions.',
    'kap.desc.p1':   'Capital renovation is a comprehensive apartment update "from scratch": full demolition of old coverings and engineering systems, levelling all surfaces, replacing electrical and plumbing, followed by finishing work.',
    'kap.desc.p2':   'Unlike cosmetic renovation, capital renovation updates everything hidden: hot and cold water pipes, sewage, electrical wiring. This ensures longevity — a properly done capital renovation lasts 15–20 years.',
    'kap.desc.p3':   'Floor screed is a mandatory stage. Without it, it\'s impossible to achieve an even base for floor coverings, underfloor heating and correct slopes in bathrooms. We lay screed with beacons to 2mm per metre accuracy.',
    'kap.desc.p4':   'Wall levelling with plaster is another key process. In standard panel buildings walls often deviate by 2–5 cm. Quality machine plastering corrects these deviations and creates a perfectly even surface for any finish.',
    'kap.desc.p5':   'In capital renovation, wiring is laid in chases or under plaster — all cables are concealed. We calculate loads for modern appliances and plan sufficient outlets in every room.',
    'kap.desc.p6':   'The result of a capital renovation by StroiGrupp is an apartment where everything works correctly and looks great. We provide a 3-year warranty on all completed works.',
    'kap.when.li1':  'Apartment not renovated for 15+ years',
    'kap.when.li2':  'Electrical or plumbing replacement needed',
    'kap.when.li3':  'Walls and floors are very uneven',
    'kap.when.li4':  'Replanning is planned',
    'kap.when.li5':  'Secondary housing before moving in',
    'kap.when.li6':  'New-build without finishing (rough state)',
    'kap.when.li7':  'Want to do it right once and for a long time',
    'kap.demo.1':    'Stripping wallpaper and tiles',
    'kap.demo.2':    'Removing floor coverings',
    'kap.demo.3':    'Demolition of non-load-bearing partitions',
    'kap.demo.4':    'Removing old screed (if required)',
    'kap.demo.5':    'Construction debris removal',
    'kap.rough.1':   'Floor screed with beacons',
    'kap.rough.2':   'Machine wall plastering',
    'kap.rough.3':   'Ceiling levelling',
    'kap.rough.4':   'Plasterboard partition construction',
    'kap.rough.5':   'Underfloor heating installation',
    'kap.elec.1':    'Electrical panel replacement',
    'kap.elec.2':    'Full wiring replacement',
    'kap.elec.3':    'Outlet and switch routing',
    'kap.elec.4':    'Lighting installation',
    'kap.elec.5':    'Electric stove and boiler connection',
    'kap.plumb.1':   'Water supply pipe replacement',
    'kap.plumb.2':   'Sewage pipe replacement',
    'kap.plumb.3':   'Toilet, bath/shower installation',
    'kap.plumb.4':   'Heating radiator connection',
    'kap.plumb.5':   'Water heater installation',
    'kap.trim.1':    'Final wall filler',
    'kap.trim.2':    'Wallpapering or painting',
    'kap.trim.3':    'Bathroom and kitchen tiling',
    'kap.trim.4':    'Laminate or parquet laying',
    'kap.trim.5':    'Ceiling installation',
    'kap.comp.1':    'Interior door installation',
    'kap.comp.2':    'Skirting and architrave installation',
    'kap.comp.3':    'Socket and switch installation',
    'kap.comp.4':    'Final cleaning',
    'kap.comp.5':    'Handover with act and warranty',
    'kap.step1.p':   'Free measurement visit. Detailed estimate broken down by work types and materials. Contract signed with fixed price, deadlines and scope of work.',
    'kap.step2.p':   'Demolition of all old coverings, partitions, old electrical and plumbing. Debris removal. Foundation condition assessment and plan adjustments as needed.',
    'kap.step3.p':   'New electrical wiring laid, water supply and sewage pipes replaced. All utilities are concealed in walls and floors before finishing work begins.',
    'kap.step4.p':   'Floor screed with beacons, machine wall plastering, ceiling levelling. These works form the even base for final coverings. Mandatory technological curing times observed.',
    'kap.step5.p':   'Filling, wallpapering or painting, bathroom tiling, laminate or parquet in rooms, ceiling installation, door and skirting board fitting.',
    'kap.step6.p':   'Socket, switch, light fixture and plumbing fixture installation. Final cleaning. Handover with act and 3-year warranty certificate.',
    'kap.mat1.p':    'Russian and Belarusian manufacturers: Knauf, Bergauf, Ceresit. Good quality at an affordable price. Recommended for rental apartments.',
    'kap.mat2.p':    'Kerama Marazzi, Atlas, Glims — trusted brands with wide assortment. Optimal price-to-quality ratio for residential renovation.',
    'kap.mat3.p':    'Weber, Mapei, Litokol, Schlueter — European materials with extended characteristics. Suitable for demanding conditions and high quality requirements.',
    'kap.svc.cos.p': 'Quick apartment appearance update. Wallpaper, paint, laminate, ceilings. Optimal for limited budgets.',
    'kap.svc.des.p': 'Bespoke design project, 3D visualisation, premium materials. Your apartment as a magazine spread.',
    'kap.svc.all.p': 'Bathroom and kitchen renovation, electrical and plumbing replacement, stretch ceilings and other works.',
    'term.6w':       '6 weeks',
    'term.6_8w':     '6–8 weeks',
    'term.8_12w':    '8–12 weeks',
    'term.12_16w':   '12–16 weeks',
    // kosmeticheskiy-remont keys
    'kos.tag.hero':  'Fast & affordable',
    'kos.h1':        'Cosmetic Apartment Renovation',
    'kos.sub':       'We\'ll transform your apartment without a major renovation. New wallpaper, paint, laminate, ceilings — and your apartment looks fresh again.',
    'kos.tag2':      'What it is',
    'kos.h2.1':      'What is cosmetic renovation?',
    'kos.aside.h3':  'When is cosmetic renovation suitable?',
    'kos.tag3':      'Scope of works',
    'kos.h2.2':      'What\'s included in cosmetic renovation',
    'kos.p2':        'Full list of works included in our turnkey cosmetic renovation',
    'kos.work1':     'Walls',
    'kos.work2':     'Ceilings',
    'kos.work3':     'Floors',
    'kos.work4':     'Doors & windows',
    'kos.work5':     'Bathroom (basic)',
    'kos.work6':     'Finishing works',
    'kos.tag4':      'Work stages',
    'kos.h2.3':      'How we do cosmetic renovation',
    'kos.p3':        'Clear process from measurement to handover',
    'kos.step1':     'Measure & estimate',
    'kos.step2':     'Contract & advance',
    'kos.step3':     'Surface preparation',
    'kos.step4':     'Final finishing',
    'kos.tag5':      'Pricing',
    'kos.h2.4':      'Cosmetic renovation prices',
    'kos.p4':        'Fixed price — cost won\'t change during renovation',
    'kos.note':      '* Price is for works only, materials not included. Get exact price after a free measurement.',
    'kos.tag6':      'FAQ',
    'kos.h2.5':      'FAQ about cosmetic renovation',
    'kos.faq1.q':    'How much does cosmetic renovation cost?',
    'kos.faq1.a':    'From 110 AED/m². Studio from 3,400 AED, 1-room from 4,800 AED, 2-room from 7,600 AED, 3-room from 10,400 AED. Materials not included.',
    'kos.faq2.q':    'How long does cosmetic renovation take?',
    'kos.faq2.a':    'Cosmetic renovation of a 1-room apartment takes 2–3 weeks. 2-room — 3–4 weeks. Deadlines are stated in the contract.',
    'kos.faq3.q':    'What\'s included in cosmetic renovation?',
    'kos.faq3.a':    'Wallpapering or wall painting, laminate flooring, baseboard installation, ceiling update, door painting or replacement, bathroom tiling.',
    'kos.faq4.q':    'Do I need to remove furniture before cosmetic renovation?',
    'kos.faq4.a':    'It\'s best to clear the space or move furniture to the center. We cover everything with film. Full clearance speeds up the work.',
    'kos.tag7':      'Other services',
    'kos.h2.6':      'Need a more thorough renovation?',
    'kos.cta.h2':    'Want to refresh your apartment?',
    'kos.cta.p':     'Message us on Telegram — we\'ll calculate the cost of cosmetic renovation for free. We reply within 15 minutes.',
    'kos.desc.p1':   'Cosmetic renovation is the renewal of an apartment\'s appearance without changing the layout, structural elements or engineering systems. It is also called "surface renovation" or "finish work".',
    'kos.desc.p2':   'The main goal is to make the apartment fresh and attractive. All visible surfaces are updated: walls, ceiling, floor, doors. Pipes, wiring and load-bearing structures are not affected.',
    'kos.desc.p3':   'Cosmetic renovation is the ideal choice when the apartment is in good condition overall but looks outdated. Yellowed wallpaper, squeaky floors, grey ceilings — classic signs it\'s time for a refresh.',
    'kos.desc.p4':   'This renovation is significantly cheaper than a capital renovation and takes much less time. We renovate a 1-room apartment in 2–3 weeks, a 2-room in 3–4 weeks. This minimises inconvenience for residents.',
    'kos.desc.p5':   'At StroiGrupp we approach cosmetic renovation professionally: careful surface preparation, quality materials and strict adherence to technology. That\'s why our results look like premium work even on a modest budget.',
    'kos.when.li1':  'Post-rental apartment — refresh the look',
    'kos.when.li2':  'Scheduled update every 5–10 years',
    'kos.when.li3':  'Preparing the apartment for sale',
    'kos.when.li4':  'New-build with finished fit-out',
    'kos.when.li5':  'Limited renovation budget',
    'kos.when.li6':  'Don\'t want to live on a construction site for months',
    'kos.walls.1':   'Plaster filling and surface levelling',
    'kos.walls.2':   'Wall priming',
    'kos.walls.3':   'Wallpapering (vinyl, non-woven)',
    'kos.walls.4':   'Wall painting in 2 coats',
    'kos.walls.5':   'Decorative plaster',
    'kos.ceil.1':    'Ceiling filling',
    'kos.ceil.2':    'Whitewashing or ceiling painting',
    'kos.ceil.3':    'Stretch ceiling installation',
    'kos.ceil.4':    'Ceiling skirting installation',
    'kos.ceil.5':    'Light fixture installation',
    'kos.floor.1':   'Laminate or parquet board laying',
    'kos.floor.2':   'Linoleum laying',
    'kos.floor.3':   'Carpet laying',
    'kos.floor.4':   'Skirting board installation',
    'kos.floor.5':   'Thresholds between rooms',
    'kos.door.1':    'Interior door painting',
    'kos.door.2':    'Interior door replacement',
    'kos.door.3':    'Window reveal painting',
    'kos.door.4':    'Architrave installation',
    'kos.door.5':    'Door hardware adjustment',
    'kos.bath.1':    'Floor and wall tiling',
    'kos.bath.2':    'Mixer and accessories replacement',
    'kos.bath.3':    'Toilet and sink replacement',
    'kos.bath.4':    'Ceiling painting',
    'kos.bath.5':    'Mirror and shelf installation',
    'kos.fin.1':     'Socket and switch replacement',
    'kos.fin.2':     'Curtain rod and curtain installation',
    'kos.fin.3':     'Post-renovation final cleaning',
    'kos.fin.4':     'Construction debris removal',
    'kos.fin.5':     'Handover sign-off',
    'kos.step1.p':   'We visit the site for free. We measure all rooms, assess surface conditions, and discuss your wishes. We prepare a detailed estimate broken down by work and materials.',
    'kos.step2.p':   'We sign a contract with a fixed price, scope of work and deadlines. You pay a 30% advance — and we immediately start purchasing materials and organising work.',
    'kos.step3.p':   'We remove old coverings: strip wallpaper, skirting boards, and level surfaces as needed. We protect furniture and windows with film. We apply primer.',
    'kos.step4.p':   'Wallpapering or wall painting, floor covering installation, skirting boards, ceiling updates. Every stage is performed to specification with quality control.',
    'kos.faq5.q':    'Can I live in the apartment during cosmetic renovation?',
    'kos.faq5.a':    'Technically yes, but it\'s uncomfortable: noise, dust, paint smell. For small apartments it\'s better to stay elsewhere. Room-by-room renovation lets you stay in the unaffected part. We always minimise disruption — we clean up at the end of every workday.',
    'kos.svc.cap.p': 'Full replacement of engineering systems, wall and floor levelling. Renovation "from scratch" built to last for decades.',
    'kos.svc.des.p': 'Bespoke design project, premium materials, unique solutions. Your apartment as a work of art.',
    'kos.svc.all.p': 'Bathroom and kitchen renovation, electrical and plumbing replacement, stretch ceilings and other individual works.',
    'apt.studio':    'Studio / Room',
    'apt.1room':     '1-bedroom',
    'apt.2room':     '2-bedroom',
    'apt.3room':     '3-bedroom',
    'term.2w':       '2 weeks',
    'term.2_3w':     '2–3 weeks',
    'term.3_4w':     '3–4 weeks',
    'term.4_5w':     '4–5 weeks',
    // dizaynersky-remont keys
    'diz.tag.hero':  'Premium format',
    'diz.h1':        'Designer Apartment Renovation',
    'diz.sub':       'A unique approach to every project. We create interiors that reflect your personality. Design project, 3D visualization, premium materials and author\'s supervision.',
    'diz.stat4':     'individual',
    'diz.btn.discuss':    'Discuss project',
    'diz.btn.portfolio':  'View portfolio',
    'diz.btn.allportfolio': 'View full portfolio',
    'diz.tag2':      'Service scope',
    'diz.h2.1':      'What designer renovation includes',
    'diz.p1':        'Full service package — from concept to final decoration',
    'diz.feat1':     'Author\'s design project',
    'diz.feat2':     '3D visualization',
    'diz.feat3':     'Material selection',
    'diz.feat4':     'Author\'s supervision',
    'diz.feat5':     'Custom solutions',
    'diz.feat6':     'Decoration & furnishing',
    'diz.tag3':      'Portfolio examples',
    'diz.h2.2':      'Designer projects by BuildGroup',
    'diz.p2':        'Several examples of completed designer renovations',
    'diz.tag4':      'Work stages',
    'diz.h2.3':      'How designer renovation is created',
    'diz.p3':        'Transparent process from first meeting to final interior photoshoot',
    'diz.step1':     'Design concept',
    'diz.step2':     '3D visualization',
    'diz.step3':     'Working documentation',
    'diz.step4':     'Construction works',
    'diz.step5':     'Author\'s supervision',
    'diz.step6':     'Decoration & handover',
    'diz.tag5':      'Pricing',
    'diz.h2.4':      'Designer renovation costs',
    'diz.price1.h3': 'Design project',
    'diz.price2.h3': 'Designer renovation',
    'diz.price3.h3': 'Decoration',
    'diz.note':      '* Construction works price excludes materials. Exact estimate is prepared after the design project is completed. Discuss your project with us on Telegram.',
    'diz.tag6':      'FAQ',
    'diz.h2.5':      'FAQ about designer renovation',
    'diz.faq1.q':    'What\'s included in designer apartment renovation?',
    'diz.faq1.a':    'Designer renovation includes: author\'s design project with 3D visualization, working documentation, selection and procurement of premium materials, full construction cycle, author\'s supervision at every stage, and final decoration.',
    'diz.faq2.q':    'How much does designer apartment renovation cost?',
    'diz.faq2.a':    'Starting from 480 AED/m² for construction works. Design project — from 60 AED/m². Final cost depends on area, architectural complexity and materials.',
    'diz.faq3.q':    'How long does designer renovation take?',
    'diz.faq3.a':    'Design project takes 3–6 weeks. Construction — 3 to 6 months. Total from first meeting to key handover — 4–8 months.',
    'diz.faq4.q':    'Is a design project required for renovation?',
    'diz.faq4.a':    'For designer renovation — yes. A design project lets you see the result before works begin, accurately calculate materials, and avoid costly rework.',
    'diz.faq5.q':    'Can I order just the design project without renovation?',
    'diz.faq5.a':    'Yes, we develop design projects separately. When ordering both design and renovation together, the project cost is reduced. Message us on Telegram to discuss terms.',
    'diz.tag7':      'Other services',
    'diz.h2.6':      'Other renovation types',
    'diz.cta.h2':    'Let\'s create your perfect interior',
    'diz.cta.p':     'Share your ideas on Telegram — our designer will contact you to discuss the concept. Consultation is free.',
    'diz.cta.btn':   'Discuss project on Telegram',
    'diz.feat1.p':   'We develop an interior concept based on your preferences, lifestyle and apartment\'s features. Measurement plan, layout solution, furniture arrangement.',
    'diz.feat2.p':   'Photorealistic 3D visualisation of every room. You\'ll see what the apartment will look like before construction begins. We can make changes at any time.',
    'diz.feat3.p':   'We create specification sheets with exact product codes. We help procure from suppliers at wholesale prices. Only trusted brands and quality products.',
    'diz.feat4.p':   'The designer monitors compliance of completed works with the project at every stage. Promptly identifies deviations and gives precise instructions to workers.',
    'diz.feat5.p':   'Multi-level ceilings, hidden lighting, niches and arches, exclusive coatings, custom built-in wardrobes. Everything that makes an interior unique.',
    'diz.feat6.p':   'Final apartment decoration: textiles, lighting, décor items. Furniture selection and arrangement on request. We hand over a fully ready apartment.',
    'diz.step1.p':   'Meeting with the designer, briefing, exploring your preferences. Apartment measurements. Concept and layout development. Agreement on overall direction.',
    'diz.step2.p':   'Photorealistic 3D visualisation of all rooms. You see the apartment before works begin. We make revisions until fully approved — no limits.',
    'diz.step3.p':   'Working drawings for all rooms: sections, elevations, specifications. Specification sheets with exact material codes. Material procurement.',
    'diz.step4.p':   'Full construction and finishing cycle in accordance with the project. Capital renovation with all engineering systems, finishing to specification.',
    'diz.step5.p':   'The designer regularly visits the site and monitors compliance with the project. Weekly photo reports. Prompt on-site resolution of technical issues.',
    'diz.step6.p':   'Furniture arrangement, textiles, lighting, décor items. Final cleaning. Professional photoshoot of the finished interior. Keys and warranty certificate handover.',
    'diz.p1.li1':    'Concept and layout',
    'diz.p1.li2':    '3D visualisation',
    'diz.p1.li3':    'Working drawings',
    'diz.p1.li4':    'Specification sheets',
    'diz.p1.li5':    'Author\'s supervision',
    'diz.p2.li1':    'All capital renovation works',
    'diz.p2.li2':    'Premium materials',
    'diz.p2.li3':    'Custom structures',
    'diz.p2.li4':    'Custom built-in furniture',
    'diz.p2.li5':    'Smart home system',
    'diz.p3.li1':    'Furniture selection',
    'diz.p3.li2':    'Textiles and curtains',
    'diz.p3.li3':    'Lighting and chandeliers',
    'diz.p3.li4':    'Décor and accessories',
    'diz.p3.li5':    'Arrangement and styling',
    'diz.svc.cos.p': 'Quick apartment refresh without major works. Optimal for limited budgets.',
    'diz.svc.cap.p': 'Full replacement of all engineering systems and finishing. Reliable for 15–20 years.',
    'diz.svc.all.p': 'Bathroom and kitchen renovation, electrical and plumbing replacement, stretch ceilings.',
  },
  ar: {
    'page.suffix':  '| ستروي غروب',
    'nav.home':     'الرئيسية',
    'nav.services': 'الخدمات',
    'nav.prices':   'الأسعار',
    'nav.portfolio':'أعمالنا',
    'nav.blog':     'المدونة',
    'nav.contacts': 'اتصل بنا',
    'nav.cosmetic': 'ترميم تجميلي',
    'nav.capital':  'ترميم شامل',
    'nav.design':   'تصميم داخلي',
    'hdr.tg':       'راسلنا',
    'footer.desc':  'تجديد شقق احترافي في موسكو منذ 2012. ضمان 3 سنوات.',
    'footer.services': 'الخدمات',
    'footer.company':  'الشركة',
    'footer.info':     'معلومات',
    'footer.copy':  '© 2024 ستروي غروب. جميع الحقوق محفوظة.',
    'footer.policy':'سياسة الخصوصية',
    'cta.title':    'هل أنت مستعد لبدء التجديد؟',
    'cta.sub':      'راسلنا عبر تيليجرام — تقدير مجاني',
    'cta.btn':      'مراسلة عبر تيليجرام',
    workerForms: ['عامل','عاملان','عمال','عمال','عمال','عمال','عمال','عمال','عمال','عمال'],
    roomNames: ['استوديو','غرفة واحدة','غرفتان','3 غرف'],
    roomSubs: ['حتى 35 م²','35–50 م²','50–75 م²','75–110 م²'],
    repairNames: ['تجميلي','شامل','تصميم داخلي'],
    vatText: (vat, total) => `+ ضريبة القيمة المضافة 20% (${vat}) = ${total} شاملة الضريبة`,
    teamText: (n) => `فريق ${n}`,
    sqm: 'م²',
    'not.selected': 'غير محدد',
    'result.hint': 'اختر نوع الترميم للحساب',
    'result.note': 'تقدير دقيق — بعد زيارة المتخصص',
    'workers.weeks': 'أسبوع',
    'workers.dur': 'المدة: ~',
    'services.h1': 'خدمات تجديد الشقق',
    'services.sub': 'دورة كاملة من أعمال التشطيب. من الترميم التجميلي إلى التصميم الداخلي المتميز.',
    'uslugi.tag1': 'ما نقدمه',
    'uslugi.tag2': 'الخدمات الرئيسية',
    'uslugi.tag3': 'أعمال إضافية',
    'uslugi.tag4': 'مزايانا',
    'uslugi.tag5': 'الأسئلة الشائعة',
    'uslugi.h2.1': 'أنواع تجديد الشقق',
    'uslugi.h2.2': 'خدمات منفردة',
    'uslugi.h2.3': 'لماذا نختار ستروي غروب',
    'uslugi.h2.4': 'الأسئلة المتكررة',
    'uslugi.cta.h2': 'احصل على استشارة مجانية',
    'uslugi.p1': 'اختر الخيار المناسب لشقتك وميزانيتك',
    'uslugi.p2': 'ننجز مهام محددة دون ترميم شامل',
    'uslugi.p3': 'نعمل لتحقيق النتائج ونبني علاقات طويلة الأمد',
    'uslugi.cta.p': 'أخبرنا عن مشروعك عبر تيليجرام — نرد خلال 15 دقيقة، تقدير مجاني',
    'uslugi.price.cos': 'من 110 AED/م²',
    'uslugi.price.cap': 'من 240 AED/م²',
    'uslugi.price.des': 'من 480 AED/م²',
    'uslugi.feat1': 'ترميم الحمام',
    'uslugi.feat2': 'ترميم المطبخ',
    'uslugi.feat3': 'أعمال الكهرباء',
    'uslugi.feat4': 'أعمال السباكة',
    'uslugi.feat5': 'أسقف مشدودة',
    'uslugi.feat6': 'أعمال الهدم',
    'uslugi.btn.price': 'احصل على سعر',
    'uslugi.adv1': 'تقدير ثابت',
    'uslugi.adv2': 'ضمان 3 سنوات',
    'uslugi.adv3': 'فرق عمل خاصة',
    'uslugi.adv4': 'الالتزام بالمواعيد',
    'uslugi.adv5': 'شراء المواد',
    'uslugi.adv6': 'تقارير إنجاز أونلاين',
    'uslugi.stat1': 'مشروع',
    'uslugi.stat2': 'في السوق',
    'uslugi.stat3': 'ضمان',
    'uslugi.stat4': 'عميل راضٍ',
    'btn.more': 'اعرف أكثر',
    'btn.estimate': 'احصل على تقدير مجاني',
    'word.free': 'مجاناً',
    'word.warranty': 'ضمان',
    'uslugi.faq1.q': 'ما أنواع التجديد التي تقدمونها؟',
    'uslugi.faq1.a': 'نقدم جميع أنواع تجديد الشقق: تجميلي (من 110 AED/م²)، شامل (من 240 AED/م²)، وتصميم داخلي (من 480 AED/م²). كما ننجز أعمالاً منفردة — حمام، مطبخ، كهرباء، سباكة، أسقف مشدودة، هدم.',
    'uslugi.faq2.q': 'هل تعملون بنظام التسليم المفتاح؟',
    'uslugi.faq2.a': 'نعم، نصيغتنا الرئيسية هي التسليم المفتاح. تستلم شقة جاهزة بالكامل — من أول مسمار حتى التنظيف النهائي. نتولى جميع الأعمال وشراء المواد وإزالة النفايات.',
    'uslugi.faq3.q': 'متى يمكنكم البدء؟',
    'uslugi.faq3.a': 'عادةً نبدأ خلال 5–7 أيام عمل بعد توقيع العقد ودفع الدفعة المقدمة. القياس والتقدير مجانيان، وغالباً يتم في يوم الاتصال أو اليوم التالي.',
    'uslugi.faq4.q': 'هل تقدمون ضماناً؟',
    'uslugi.faq4.a': 'نعم، نقدم ضماناً مكتوباً لمدة 3 سنوات على جميع أعمال التجديد. الضمان مذكور في العقد. إذا ظهرت عيوب بسببنا، نصلحها مجاناً خلال 5 أيام عمل.',
    'uslugi.faq5.q': 'ما المناطق التي تخدمونها؟',
    'uslugi.faq5.a': 'نعمل في موسكو وضواحيها. زيارة المتخصص للقياس مجانية. نقبل أيضاً طلبات من مناطق أخرى — ناقشوا التفاصيل عبر تيليجرام.',
    // common new keys
    'btn.prices':    'عرض الأسعار',
    'btn.order':     'اطلب الآن',
    'btn.pricelist': 'قائمة الأسعار الكاملة',
    'tbl.type':      'نوع الشقة',
    'tbl.area':      'المساحة',
    'tbl.cost':      'تكلفة الأعمال',
    'tbl.term':      'المدة',
    'kap.stat1':     'لكل م²',
    'kap.stat2':     'مدة الأعمال',
    'kap.stat3':     'ضمان',
    'kap.stat4':     'قياس وتقدير',
    // kapitalnyy-remont keys
    'kap.tag.hero':  'ترميم كامل',
    'kap.h1':        'ترميم شامل للشقة',
    'kap.sub':       'دورة كاملة من أعمال التجديد: من الهدم إلى التشطيب النهائي. كهرباء وسباكة وأرضية وجدران جديدة — شقة متجددة لمدة 15–20 عاماً.',
    'kap.tag2':      'ما هو',
    'kap.h2.1':      'ما هو الترميم الشامل؟',
    'kap.aside.h3':  'متى تحتاج إلى ترميم شامل؟',
    'kap.tag3':      'نطاق الأعمال',
    'kap.h2.2':      'ما يشمله الترميم الشامل',
    'kap.p2':        'القائمة الكاملة للأعمال في الترميم الشامل',
    'kap.work1':     'هدم',
    'kap.work2':     'أعمال خام',
    'kap.work3':     'كهرباء',
    'kap.work4':     'سباكة',
    'kap.work5':     'تشطيب وتزيين',
    'kap.work6':     'الإنجاز',
    'kap.tag4':      'مراحل العمل',
    'kap.h2.3':      'مراحل الترميم الشامل',
    'kap.p3':        'عملية منضبطة من التوقيع على العقد حتى تسليم المفاتيح',
    'kap.step1':     'قياس وتقدير وعقد',
    'kap.step2':     'هدم وتحضير',
    'kap.step3':     'أعمال مخفية',
    'kap.step4':     'التشطيب الخام',
    'kap.step5':     'التشطيب النهائي',
    'kap.step6':     'تسليم المشروع',
    'kap.tag5':      'التسعير',
    'kap.h2.4':      'أسعار الترميم الشامل',
    'kap.p4':        'سعر ثابت — لن تتغير التكلفة أثناء التجديد',
    'kap.note':      '* السعر للأعمال فقط، لا يشمل المواد. احصل على السعر الدقيق بعد زيارة القياس المجانية.',
    'kap.tag6':      'المواد',
    'kap.h2.5':      'مواد الترميم الشامل',
    'kap.p5':        'نعمل مع مصنّعين موثوقين ونساعد في اختيار المواد المثلى لميزانيتك',
    'kap.mat1':      'فئة اقتصادية',
    'kap.mat2':      'فئة متوسطة',
    'kap.mat3':      'فاخر',
    'kap.tag7':      'الأسئلة الشائعة',
    'kap.h2.6':      'أسئلة شائعة عن الترميم الشامل',
    'kap.faq1.q':    'كم يكلف الترميم الشامل للشقة؟',
    'kap.faq1.a':    'يبدأ من 240 AED/م². استوديو من 8,400 AED، غرفة واحدة من 12,000 AED، غرفتان من 19,200 AED، 3 غرف من 26,000 AED. لا تشمل المواد.',
    'kap.faq2.q':    'كم تستغرق عملية الترميم الشامل؟',
    'kap.faq2.a':    'من 6 إلى 16 أسبوعاً حسب المساحة: غرفة واحدة 6–8 أسابيع، غرفتان 8–12 أسبوعاً، 3 غرف 12–16 أسبوعاً.',
    'kap.faq3.q':    'ما الفرق بين الترميم الشامل والتجميلي؟',
    'kap.faq3.a':    'التجميلي — تجديد الأسطح دون تغيير الأنظمة الهندسية. الشامل — تجديد كامل مع استبدال الكهرباء والسباكة والأرضية والجدران. النتيجة تدوم 15–20 عاماً.',
    'kap.faq4.q':    'هل يلزم الحصول على موافقة للترميم الشامل؟',
    'kap.faq4.a':    'إذا لم تغير التخطيط — لا حاجة لموافقة. إذا كنت تهدم/تبني جدراناً أو تنقل المطبخ — تلزم الموافقة. نساعد في التوثيق.',
    'kap.faq5.q':    'هل يمكن الدفع على مراحل؟',
    'kap.faq5.a':    'نعم، النظام الافتراضي: 30% دفعة مقدمة، 40% بعد الأعمال الخام، 30% عند التسليم النهائي. الجدول مذكور في العقد.',
    'kap.tag8':      'خدمات أخرى',
    'kap.h2.7':      'أنواع التجديد الأخرى',
    'kap.allsvc':    'جميع الخدمات',
    'kap.viewall':   'عرض الكل',
    'kap.onrequest': 'عند الطلب',
    'kap.cta.h2':    'هل أنت مستعد للحديث عن تجديد شقتك؟',
    'kap.cta.p':     'راسلنا عبر تيليجرام — سنحسب تكلفة الترميم الشامل مجاناً ونجيب على جميع أسئلتك.',
    'kap.desc.p1':   'الترميم الشامل هو تجديد شامل للشقة "من الصفر": هدم كامل للتشطيبات القديمة والأنظمة الهندسية، وتسوية جميع الأسطح، واستبدال الكهرباء والسباكة، ثم التشطيب النهائي.',
    'kap.desc.p2':   'بخلاف الترميم التجميلي، يشمل الترميم الشامل تجديد كل شيء مخفي: أنابيب المياه الباردة والساخنة، الصرف الصحي، الأسلاك الكهربائية. هذا ما يضمن المتانة — الترميم الشامل الصحيح يدوم 15–20 عاماً.',
    'kap.desc.p3':   'صب الأرضية (السكريد) مرحلة إلزامية. بدونها يستحيل تحقيق قاعدة مستوية للأرضية والتدفئة الأرضية والانحدار الصحيح في الحمامات. نضع السكريد بالمستويات بدقة 2 ملم في المتر.',
    'kap.desc.p4':   'تسوية الجدران بالجص عملية رئيسية أخرى. في المباني اللوحية الاعتيادية كثيراً ما تنحرف الجدران 2–5 سم. يصحح الجص الآلي الجيد هذه الانحرافات ويخلق سطحاً مستوياً تماماً لأي تشطيب.',
    'kap.desc.p5':   'في الترميم الشامل تُمدّ الأسلاك في قنوات أو تحت الجص — جميع الكابلات مخفية. نحسب الأحمال للأجهزة الحديثة ونخطط لعدد كافٍ من المقابس في كل غرفة.',
    'kap.desc.p6':   'نتيجة الترميم الشامل من ستروي غروب — شقة يعمل فيها كل شيء بشكل صحيح وتبدو رائعة. نقدم ضمان 3 سنوات على جميع الأعمال المنجزة.',
    'kap.when.li1':  'شقة لم تُجدَّد منذ 15+ عاماً',
    'kap.when.li2':  'الكهرباء أو الأنابيب تحتاج إلى استبدال',
    'kap.when.li3':  'الجدران والأرضيات غير مستوية',
    'kap.when.li4':  'مخطط لإعادة تصميم',
    'kap.when.li5':  'سكن ثانوي قبل الانتقال',
    'kap.when.li6':  'مبنى جديد بدون تشطيب (هيكل خام)',
    'kap.when.li7':  'تريد إنجاز كل شيء مرة واحدة وإلى الأبد',
    'kap.demo.1':    'إزالة ورق الحائط والبلاط',
    'kap.demo.2':    'إزالة الأرضيات',
    'kap.demo.3':    'هدم الجدران الفاصلة غير الحاملة',
    'kap.demo.4':    'إزالة السكريد القديم (عند الحاجة)',
    'kap.demo.5':    'إزالة مخلفات البناء',
    'kap.rough.1':   'صب السكريد بالمستويات',
    'kap.rough.2':   'تجصيص الجدران آلياً',
    'kap.rough.3':   'تسوية الأسقف',
    'kap.rough.4':   'إنشاء جدران فاصلة من الجبسبورد',
    'kap.rough.5':   'تركيب التدفئة الأرضية',
    'kap.elec.1':    'استبدال لوحة الكهرباء',
    'kap.elec.2':    'استبدال كامل للأسلاك',
    'kap.elec.3':    'توزيع المقابس والمفاتيح',
    'kap.elec.4':    'تركيب الإضاءة',
    'kap.elec.5':    'توصيل البوتاجاز والسخان الكهربائي',
    'kap.plumb.1':   'استبدال أنابيب إمداد المياه',
    'kap.plumb.2':   'استبدال أنابيب الصرف',
    'kap.plumb.3':   'تركيب المرحاض والحوض/الدش',
    'kap.plumb.4':   'توصيل مشعات التدفئة',
    'kap.plumb.5':   'تركيب سخان المياه',
    'kap.trim.1':    'معجنة نهائية للجدران',
    'kap.trim.2':    'تركيب ورق الحائط أو الطلاء',
    'kap.trim.3':    'تبليط الحمام والمطبخ',
    'kap.trim.4':    'فرش لامينيت أو باركيه',
    'kap.trim.5':    'تركيب الأسقف',
    'kap.comp.1':    'تركيب الأبواب الداخلية',
    'kap.comp.2':    'تركيب القواعد والإطارات الزخرفية',
    'kap.comp.3':    'تركيب المقابس والمفاتيح',
    'kap.comp.4':    'التنظيف النهائي',
    'kap.comp.5':    'تسليم المشروع بضمان رسمي',
    'kap.step1.p':   'زيارة قياس مجانية. إعداد تقدير تفصيلي مُقسَّم حسب أنواع الأعمال والمواد. توقيع عقد بسعر ثابت ومواعيد وقائمة أعمال.',
    'kap.step2.p':   'هدم جميع التشطيبات القديمة والجدران والكهرباء والسباكة. إزالة المخلفات. تقييم حالة الأساسات وتعديل الخطط عند الحاجة.',
    'kap.step3.p':   'تمديد أسلاك كهربائية جديدة، استبدال أنابيب المياه والصرف. تُخفى جميع الأنظمة في الجدران والأرضية قبل بدء أعمال التشطيب.',
    'kap.step4.p':   'صب السكريد بالمستويات، تجصيص الجدران آلياً، تسوية الأسقف. تشكّل هذه الأعمال القاعدة المستوية للتشطيب النهائي. مراعاة فترات التصليد الإلزامية.',
    'kap.step5.p':   'معجنة، تركيب ورق حائط أو طلاء، تبليط الحمام، فرش لامينيت أو باركيه في الغرف، تركيب أسقف وأبواب وقواعد.',
    'kap.step6.p':   'تركيب المقابس والمفاتيح والإضاءة وتجهيزات السباكة. التنظيف النهائي. التسليم مع محضر واستمارة ضمان لمدة 3 سنوات.',
    'kap.mat1.p':    'مصنّعون روس وبيلاروس: Knauf، Bergauf، Ceresit. جودة جيدة بسعر مناسب. موصى به للشقق المخصصة للإيجار.',
    'kap.mat2.p':    'Kerama Marazzi، Atlas، Glims — علامات موثوقة بتشكيلة واسعة. أفضل نسبة سعر/جودة للترميم السكني.',
    'kap.mat3.p':    'Weber، Mapei، Litokol، Schlueter — مواد أوروبية بخصائص موسّعة. مناسبة لظروف الاستخدام الصعبة والمتطلبات العالية للجودة.',
    'kap.svc.cos.p': 'تحديث سريع لمظهر الشقة. ورق حائط وطلاء ولامينيت وأسقف. الخيار الأمثل للميزانيات المحدودة.',
    'kap.svc.des.p': 'مشروع تصميم حصري، نمذجة ثلاثية الأبعاد، مواد فاخرة. شقتك كما في صفحات المجلات.',
    'kap.svc.all.p': 'ترميم الحمام والمطبخ، استبدال الكهرباء والسباكة، أسقف مشدودة وأعمال أخرى.',
    'term.6w':       '6 أسابيع',
    'term.6_8w':     '6–8 أسابيع',
    'term.8_12w':    '8–12 أسبوعاً',
    'term.12_16w':   '12–16 أسبوعاً',
    // kosmeticheskiy-remont keys
    'kos.tag.hero':  'سريع وبأسعار معقولة',
    'kos.h1':        'ترميم تجميلي للشقة',
    'kos.sub':       'سنحوّل شقتك دون ترميم كامل. ورق حائط وطلاء وأرضية وأسقف جديدة — وشقتك تبدو جديدة مرة أخرى.',
    'kos.tag2':      'ما هو',
    'kos.h2.1':      'ما هو الترميم التجميلي؟',
    'kos.aside.h3':  'متى يناسب الترميم التجميلي؟',
    'kos.tag3':      'نطاق الأعمال',
    'kos.h2.2':      'ما يشمله الترميم التجميلي',
    'kos.p2':        'القائمة الكاملة للأعمال في الترميم التجميلي الشامل',
    'kos.work1':     'الجدران',
    'kos.work2':     'الأسقف',
    'kos.work3':     'الأرضيات',
    'kos.work4':     'الأبواب والنوافذ',
    'kos.work5':     'الحمام (أساسي)',
    'kos.work6':     'أعمال الختام',
    'kos.tag4':      'مراحل العمل',
    'kos.h2.3':      'كيف ننفذ الترميم التجميلي',
    'kos.p3':        'عملية واضحة من القياس حتى التسليم',
    'kos.step1':     'قياس وتقدير',
    'kos.step2':     'عقد ودفعة مقدمة',
    'kos.step3':     'تحضير الأسطح',
    'kos.step4':     'التشطيب النهائي',
    'kos.tag5':      'التسعير',
    'kos.h2.4':      'أسعار الترميم التجميلي',
    'kos.p4':        'سعر ثابت — لن تتغير التكلفة أثناء التجديد',
    'kos.note':      '* السعر للأعمال فقط، لا يشمل المواد. احصل على السعر الدقيق بعد القياس المجاني.',
    'kos.tag6':      'الأسئلة الشائعة',
    'kos.h2.5':      'أسئلة حول الترميم التجميلي',
    'kos.faq1.q':    'كم يكلف الترميم التجميلي للشقة؟',
    'kos.faq1.a':    'من 110 AED/م². استوديو من 3,400 AED، غرفة واحدة من 4,800 AED، غرفتان من 7,600 AED، 3 غرف من 10,400 AED. لا تشمل المواد.',
    'kos.faq2.q':    'كم يستغرق الترميم التجميلي؟',
    'kos.faq2.a':    'يستغرق الترميم التجميلي لشقة غرفة واحدة 2–3 أسابيع. غرفتان: 3–4 أسابيع. المواعيد مذكورة في العقد.',
    'kos.faq3.q':    'ماذا يشمل الترميم التجميلي؟',
    'kos.faq3.a':    'ورق حائط أو طلاء جدران، أرضية لامينيت، تركيب قواعد الجدران، تحديث الأسقف، طلاء أو استبدال الأبواب، تركيب بلاط الحمام.',
    'kos.faq4.q':    'هل أحتاج إلى إزالة الأثاث قبل الترميم التجميلي؟',
    'kos.faq4.a':    'يُفضَّل إخلاء المكان أو نقل الأثاث إلى المركز. نغطي كل شيء بالنيلون. الإخلاء الكامل يسرّع العمل.',
    'kos.tag7':      'خدمات أخرى',
    'kos.h2.6':      'هل تحتاج إلى ترميم أشمل؟',
    'kos.cta.h2':    'هل تريد تجديد شقتك؟',
    'kos.cta.p':     'راسلنا عبر تيليجرام — سنحسب تكلفة الترميم التجميلي مجاناً. نرد خلال 15 دقيقة.',
    'kos.desc.p1':   'الترميم التجميلي هو تجديد مظهر الشقة دون تغيير المخطط أو العناصر الإنشائية أو الأنظمة الهندسية. يُعرف أيضاً بـ"ترميم الأسطح" أو "التشطيب النهائي".',
    'kos.desc.p2':   'الهدف الرئيسي من الترميم التجميلي هو جعل الشقة منعشة وجذابة. تُجدَّد جميع الأسطح المرئية: الجدران والسقف والأرضية والأبواب. لا تُمَس الأنابيب والأسلاك والهياكل الحاملة.',
    'kos.desc.p3':   'الترميم التجميلي هو الخيار الأمثل إذا كانت الشقة في حالة جيدة عموماً لكن مظهرها قديم. ورق حائط متصفر وأرضيات تئن وأسقف رمادية — علامات واضحة على أن الوقت حان للتجديد.',
    'kos.desc.p4':   'هذا النوع من الترميم أرخص بكثير من الترميم الشامل ويستغرق وقتاً أقل. نجدد شقة غرفة واحدة في 2–3 أسابيع وشقة غرفتين في 3–4 أسابيع، مما يقلل الإزعاج للسكان إلى أدنى حد.',
    'kos.desc.p5':   'في ستروي غروب نتعامل مع الترميم التجميلي باحترافية: نحضّر الأسطح بعناية ونستخدم مواد عالية الجودة ونلتزم بالتقنيات. لهذا تبدو نتائج عملنا كترميم فاخر حتى في ميزانية محدودة.',
    'kos.when.li1':  'شقة ما بعد الإيجار — لتجديد المظهر',
    'kos.when.li2':  'تحديث دوري كل 5–10 سنوات',
    'kos.when.li3':  'تحضير الشقة للبيع',
    'kos.when.li4':  'مبنى جديد بتشطيب كامل',
    'kos.when.li5':  'ميزانية ترميم محدودة',
    'kos.when.li6':  'عدم الرغبة في العيش في ورشة بناء لأشهر',
    'kos.walls.1':   'معجنة وتسوية الأسطح',
    'kos.walls.2':   'تأسيس الجدران',
    'kos.walls.3':   'تركيب ورق الحائط (فينيل، فلايزلاين)',
    'kos.walls.4':   'طلاء الجدران بطبقتين',
    'kos.walls.5':   'جص زخرفي',
    'kos.ceil.1':    'معجنة السقف',
    'kos.ceil.2':    'تبييض أو طلاء السقف',
    'kos.ceil.3':    'تركيب سقف مشدود',
    'kos.ceil.4':    'تركيب قاعدة السقف',
    'kos.ceil.5':    'تركيب الإضاءة',
    'kos.floor.1':   'فرش لامينيت أو باركيه',
    'kos.floor.2':   'فرش لينوليوم',
    'kos.floor.3':   'فرش سجادة',
    'kos.floor.4':   'تركيب قواعد الجدران الأرضية',
    'kos.floor.5':   'عتبات بين الغرف',
    'kos.door.1':    'طلاء الأبواب الداخلية',
    'kos.door.2':    'استبدال الأبواب الداخلية',
    'kos.door.3':    'طلاء كسوة النوافذ',
    'kos.door.4':    'تركيب الإطارات الزخرفية',
    'kos.door.5':    'ضبط تجهيزات الأبواب',
    'kos.bath.1':    'تبليط الأرضية والجدران',
    'kos.bath.2':    'استبدال الخلاطات والإكسسوارات',
    'kos.bath.3':    'استبدال المرحاض والمغسلة',
    'kos.bath.4':    'طلاء السقف',
    'kos.bath.5':    'تركيب المرايا والرفوف',
    'kos.fin.1':     'استبدال المقابس والمفاتيح',
    'kos.fin.2':     'تركيب أعمدة الستائر والستائر',
    'kos.fin.3':     'التنظيف النهائي بعد الترميم',
    'kos.fin.4':     'إزالة مخلفات البناء',
    'kos.fin.5':     'تسليم المشروع رسمياً',
    'kos.step1.p':   'نزور الموقع مجاناً. نقيس جميع الغرف ونقيّم حالة الأسطح ونناقش رغباتكم. نُعدّ تقديراً تفصيلياً مُقسَّماً حسب الأعمال والمواد.',
    'kos.step2.p':   'نوقّع عقداً بسعر ثابت وقائمة أعمال ومواعيد. تدفعون دفعة مقدمة 30% — ونبدأ فوراً في شراء المواد وتنظيم العمل.',
    'kos.step3.p':   'نزيل التشطيبات القديمة: نقشر ورق الحائط وقواعد الجدران ونسوّي الأسطح عند الحاجة. نحمي الأثاث والنوافذ بالنيلون. نُطبّق مادة التأسيس.',
    'kos.step4.p':   'تركيب ورق الحائط أو طلاء الجدران، وفرش الأرضية، وتركيب القواعد، وتجديد الأسقف. كل مرحلة تُنفَّذ وفق التقنية الصحيحة مع مراقبة الجودة.',
    'kos.faq5.q':    'هل يمكن السكن في الشقة أثناء الترميم التجميلي؟',
    'kos.faq5.a':    'من الناحية التقنية نعم، لكنه غير مريح: ضوضاء وغبار ورائحة طلاء. إذا كانت الشقة صغيرة يُفضَّل الإقامة عند الأقارب أو استئجار مكان مؤقت. عند الترميم غرفة بغرفة يمكن البقاء في الجزء غير المتأثر. نحرص دائماً على تقليل الإزعاج — ننظف في نهاية كل يوم عمل.',
    'kos.svc.cap.p': 'استبدال كامل للأنظمة الهندسية، تسوية الجدران والأرضية. ترميم "من الصفر" لسنوات طويلة.',
    'kos.svc.des.p': 'مشروع تصميم حصري، مواد فاخرة، حلول غير تقليدية. شقتك — تحفة فنية.',
    'kos.svc.all.p': 'ترميم الحمام والمطبخ، استبدال الكهرباء والسباكة، أسقف مشدودة وأعمال أخرى.',
    'apt.studio':    'استوديو / غرفة',
    'apt.1room':     'شقة غرفة واحدة',
    'apt.2room':     'شقة غرفتان',
    'apt.3room':     'شقة 3 غرف',
    'term.2w':       'أسبوعان',
    'term.2_3w':     '2–3 أسابيع',
    'term.3_4w':     '3–4 أسابيع',
    'term.4_5w':     '4–5 أسابيع',
    // dizaynersky-remont keys
    'diz.tag.hero':  'صيغة متميزة',
    'diz.h1':        'تصميم داخلي للشقة',
    'diz.sub':       'نهج فريد لكل مشروع. نصنع ديكورات داخلية تعكس شخصيتك. مشروع تصميم، محاكاة ثلاثية الأبعاد، مواد فاخرة وإشراف المصمم.',
    'diz.stat4':     'فردي',
    'diz.btn.discuss':    'ناقش المشروع',
    'diz.btn.portfolio':  'مشاهدة الأعمال',
    'diz.btn.allportfolio': 'مشاهدة كل الأعمال',
    'diz.tag2':      'نطاق الخدمة',
    'diz.h2.1':      'ما يشمله تجديد التصميم الداخلي',
    'diz.p1':        'حزمة خدمات كاملة — من المفهوم إلى الديكور النهائي',
    'diz.feat1':     'مشروع تصميم أصيل',
    'diz.feat2':     'محاكاة ثلاثية الأبعاد',
    'diz.feat3':     'اختيار المواد',
    'diz.feat4':     'إشراف المصمم',
    'diz.feat5':     'حلول مخصصة',
    'diz.feat6':     'ديكور وأثاث',
    'diz.tag3':      'أمثلة من أعمالنا',
    'diz.h2.2':      'مشاريع التصميم الداخلي لدينا',
    'diz.p2':        'بعض الأمثلة على تجديدات التصميم الداخلي المنجزة',
    'diz.tag4':      'مراحل العمل',
    'diz.h2.3':      'كيف يُنجز تجديد التصميم الداخلي',
    'diz.p3':        'عملية شفافة من الاجتماع الأول حتى التصوير النهائي للديكور',
    'diz.step1':     'مفهوم التصميم',
    'diz.step2':     'محاكاة ثلاثية الأبعاد',
    'diz.step3':     'الوثائق الإنشائية',
    'diz.step4':     'أعمال البناء',
    'diz.step5':     'إشراف المصمم',
    'diz.step6':     'الديكور والتسليم',
    'diz.tag5':      'التسعير',
    'diz.h2.4':      'تكاليف تجديد التصميم الداخلي',
    'diz.price1.h3': 'مشروع التصميم',
    'diz.price2.h3': 'تجديد التصميم الداخلي',
    'diz.price3.h3': 'الديكور',
    'diz.note':      '* سعر أعمال البناء لا يشمل المواد. يُعدّ التقدير الدقيق بعد الانتهاء من مشروع التصميم. ناقش مشروعك معنا عبر تيليجرام.',
    'diz.tag6':      'الأسئلة الشائعة',
    'diz.h2.5':      'أسئلة شائعة عن تجديد التصميم الداخلي',
    'diz.faq1.q':    'ما الذي يشمله تجديد التصميم الداخلي؟',
    'diz.faq1.a':    'يشمل: مشروع تصميم أصيل مع محاكاة ثلاثية الأبعاد، وثائق إنشائية، اختيار وشراء مواد فاخرة، دورة كاملة من أعمال البناء، إشراف المصمم في كل مرحلة، والديكور النهائي.',
    'diz.faq2.q':    'كم يكلف تجديد التصميم الداخلي؟',
    'diz.faq2.a':    'يبدأ من 480 AED/م² لأعمال البناء. مشروع التصميم من 60 AED/م². التكلفة النهائية تعتمد على المساحة والتعقيد والمواد.',
    'diz.faq3.q':    'كم يستغرق تجديد التصميم الداخلي؟',
    'diz.faq3.a':    'مشروع التصميم يستغرق 3–6 أسابيع. أعمال البناء 3–6 أشهر. المجموع من الاجتماع الأول حتى تسليم المفاتيح: 4–8 أشهر.',
    'diz.faq4.q':    'هل مشروع التصميم ضروري للترميم؟',
    'diz.faq4.a':    'لتجديد التصميم الداخلي — نعم. مشروع التصميم يتيح رؤية النتيجة قبل البدء، وحساب المواد بدقة، وتجنب إعادة العمل.',
    'diz.faq5.q':    'هل يمكن طلب مشروع التصميم فقط دون ترميم؟',
    'diz.faq5.a':    'نعم، نُعدّ مشاريع تصميم بشكل مستقل. عند الطلب المشترك للتصميم والترميم تنخفض تكلفة المشروع. راسلنا عبر تيليجرام لمناقشة الشروط.',
    'diz.tag7':      'خدمات أخرى',
    'diz.h2.6':      'أنواع الترميم الأخرى',
    'diz.cta.h2':    'سنصنع ديكورك المثالي',
    'diz.cta.p':     'أخبرنا بأفكارك عبر تيليجرام — سيتواصل معك مصممنا لمناقشة المفهوم. الاستشارة مجانية.',
    'diz.cta.btn':   'ناقش المشروع عبر تيليجرام',
    'diz.feat1.p':   'نطور مفهوم الديكور الداخلي مع مراعاة تفضيلاتك وأسلوب حياتك وخصائص الشقة. مخطط القياس وحل التخطيط وترتيب الأثاث.',
    'diz.feat2.p':   'نمذجة ثلاثية الأبعاد فوتوواقعية لكل غرفة. ستشاهد كيف ستبدو الشقة قبل بدء أعمال البناء. يمكن إجراء تغييرات في أي وقت.',
    'diz.feat3.p':   'نُعدّ قوائم تجهيز بأرقام المنتجات الدقيقة. نساعد في الشراء من الموردين بأسعار الجملة. علامات موثوقة فقط ومنتجات ذات جودة.',
    'diz.feat4.p':   'يراقب المصمم مطابقة الأعمال المنجزة للمشروع في كل مرحلة. يكتشف الانحرافات في الوقت المناسب ويعطي العمال تعليمات دقيقة.',
    'diz.feat5.p':   'أسقف متعددة المستويات، إضاءة خفية، حنيات وأقواس، تشطيبات حصرية، خزائن مدمجة بمقاسات مخصصة. كل ما يجعل الديكور الداخلي فريداً.',
    'diz.feat6.p':   'الديكور النهائي للشقة: منسوجات وإضاءة وعناصر زخرفية. اختيار وترتيب الأثاث عند الطلب. نسلمك شقة جاهزة بالكامل.',
    'diz.step1.p':   'لقاء مع المصمم، استبيان، استكشاف تفضيلاتك. قياس الشقة. تطوير المفهوم وحلول التخطيط. الاتفاق على التوجه العام.',
    'diz.step2.p':   'نمذجة ثلاثية الأبعاد فوتوواقعية لجميع الغرف. ترى الشقة قبل بدء الأعمال. نجري تعديلات حتى الموافقة الكاملة — بلا قيود.',
    'diz.step3.p':   'رسومات إنشائية لجميع الغرف: مقاطع وارتفاعات ومواصفات. قوائم تجهيز بأرقام مواد دقيقة. شراء المواد.',
    'diz.step4.p':   'دورة كاملة من أعمال البناء والتشطيب وفق المشروع. ترميم شامل بجميع الأنظمة الهندسية، وتشطيب نهائي وفق المواصفات.',
    'diz.step5.p':   'يزور المصمم الموقع بانتظام ويراقب مطابقة الأعمال للمشروع. تقارير صور أسبوعية. حل فوري للمسائل التقنية في الموقع.',
    'diz.step6.p':   'ترتيب الأثاث والمنسوجات والإضاءة وعناصر الديكور. التنظيف النهائي. تصوير احترافي للديكور المكتمل. تسليم المفاتيح وبطاقة الضمان.',
    'diz.p1.li1':    'المفهوم والتخطيط',
    'diz.p1.li2':    'نمذجة ثلاثية الأبعاد',
    'diz.p1.li3':    'رسومات إنشائية',
    'diz.p1.li4':    'قوائم التجهيز',
    'diz.p1.li5':    'إشراف المصمم',
    'diz.p2.li1':    'جميع أعمال الترميم الشامل',
    'diz.p2.li2':    'مواد فاخرة',
    'diz.p2.li3':    'هياكل مخصصة',
    'diz.p2.li4':    'أثاث مدمج على المقاس',
    'diz.p2.li5':    'نظام المنزل الذكي',
    'diz.p3.li1':    'اختيار الأثاث',
    'diz.p3.li2':    'منسوجات وستائر',
    'diz.p3.li3':    'إضاءة وثريات',
    'diz.p3.li4':    'ديكور وإكسسوارات',
    'diz.p3.li5':    'ترتيب وتنسيق',
    'diz.svc.cos.p': 'تحديث سريع للشقة دون أعمال كبرى. الخيار الأمثل للميزانيات المحدودة.',
    'diz.svc.cap.p': 'استبدال كامل لجميع الأنظمة الهندسية وتشطيب نهائي. موثوق لمدة 15–20 عاماً.',
    'diz.svc.all.p': 'ترميم الحمام والمطبخ، استبدال الكهرباء والسباكة، أسقف مشدودة.',
  }
};

/* ── LANG STATE ── */
let currentLang = localStorage.getItem('sg-lang') || 'ru';

function setLang(lang) {
  currentLang = lang;
  localStorage.setItem('sg-lang', lang);
  const html = document.documentElement;
  html.setAttribute('lang', lang);
  html.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');

  // text
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (T[lang][key] !== undefined) {
      const val = T[lang][key];
      if (typeof val === 'string' && val.includes('<')) el.innerHTML = val;
      else el.textContent = val;
    }
  });

  // placeholders
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.dataset.i18nPlaceholder;
    if (T[lang][key]) el.placeholder = T[lang][key];
  });

  // innerHTML explicit
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.dataset.i18nHtml;
    if (T[lang][key]) el.innerHTML = T[lang][key];
  });

  // lang buttons
  document.querySelectorAll('.lang-btn').forEach(b =>
    b.classList.toggle('active', b.dataset.lang === lang)
  );

  // page-specific refresh
  if (typeof refreshPageLang === 'function') refreshPageLang(lang);
}

function initLang() {
  document.documentElement.setAttribute('lang', currentLang);
  document.documentElement.setAttribute('dir', currentLang === 'ar' ? 'rtl' : 'ltr');
  setLang(currentLang);
}

/* ── FAQ ACCORDION ── */
function initFAQ() {
  document.querySelectorAll('.faq-item').forEach(item => {
    const q = item.querySelector('.faq-q');
    if (!q) return;
    q.addEventListener('click', () => {
      const isOpen = item.classList.contains('open');
      document.querySelectorAll('.faq-item.open').forEach(i => i.classList.remove('open'));
      if (!isOpen) item.classList.add('open');
    });
  });
}

/* ── SMOOTH SCROLL ── */
function initScroll() {
  document.querySelectorAll('a[href^="#"]').forEach(a => {
    a.addEventListener('click', e => {
      const t = document.querySelector(a.getAttribute('href'));
      if (t) { e.preventDefault(); t.scrollIntoView({ behavior: 'smooth' }); }
    });
  });
}

/* ── RANGE TRACK ── */
function updateRangeTrack(input) {
  const pct = (input.value - input.min) / (input.max - input.min) * 100;
  input.style.background =
    `linear-gradient(to right, var(--accent) ${pct}%, var(--border) ${pct}%)`;
}

function initRanges() {
  document.querySelectorAll('input[type="range"]').forEach(r => {
    updateRangeTrack(r);
    r.addEventListener('input', () => updateRangeTrack(r));
  });
}

/* ── FILTER TABS ── */
function initFilters() {
  document.querySelectorAll('.filter-tabs').forEach(tabs => {
    tabs.querySelectorAll('.ftab').forEach(tab => {
      tab.addEventListener('click', () => {
        tabs.querySelectorAll('.ftab').forEach(t => t.classList.remove('active'));
        tab.classList.add('active');
        const target = tab.dataset.filter;
        const container = document.querySelector(tabs.dataset.container);
        if (!container) return;
        container.querySelectorAll('[data-cat]').forEach(item => {
          item.style.display = (target === 'all' || item.dataset.cat === target) ? '' : 'none';
        });
      });
    });
  });
}

/* ── PHONE FORMAT ── */
function initPhone() {
  document.querySelectorAll('input[type="tel"]').forEach(input => {
    input.addEventListener('input', function() {
      let v = this.value.replace(/\D/g, '');
      if (!v) return;
      if (v[0] === '7' || v[0] === '8') v = v.slice(1);
      let r = '+7';
      if (v.length > 0) r += ' (' + v.slice(0, 3);
      if (v.length >= 3) r += ') ' + v.slice(3, 6);
      if (v.length >= 6) r += '-' + v.slice(6, 8);
      if (v.length >= 8) r += '-' + v.slice(8, 10);
      this.value = r;
    });
  });
}

/* ── FORM SUBMIT → TELEGRAM ── */
function initForms() {
  document.querySelectorAll('form[data-tg-form]').forEach(form => {
    form.addEventListener('submit', e => {
      e.preventDefault();
      const successEl = document.getElementById('formSuccess');
      if (successEl) {
        form.style.display = 'none';
        successEl.classList.add('show');
      }
      // Open Telegram
      setTimeout(() => window.open(TG_LINK, '_blank'), 600);
    });
  });
}

/* ── INIT ── */
document.addEventListener('DOMContentLoaded', () => {
  initLang();
  initFAQ();
  initScroll();
  initRanges();
  initFilters();
  initPhone();
  initForms();
});
